### ISSUE TITLE
Pressing the Enter key in "Security settings" form throws error

### ISSUE THREAD

**Issue by busla** [mailpile/Mailpile#1044]
![screen shot 2014-10-10 at 23 00 13](https://cloud.githubusercontent.com/assets/3162968/4600259/607d5a92-50d1-11e4-8165-7864a4bbf6bf.png)

Pressing the enter in this form throws "Invortis eymsli" error.

**Comment by a42** [comment]
I'm experiencing this on my external server installation, I have done a git pull and therefore uptodate...

Is there a way to fix this ?

Cheers!

Adam

**Comment by bnvk** [comment]
@a42 are you using a foreign language by chance?

**Comment by a42** [comment]
@bnvk yep! Danish as I am from Denmark :) any known problems in this ?

**Comment by bnvk** [comment]
Ok, re-opening this issue as the request to save settings (after entering the confirmation password) is now 500'ing. Here is the stack trace:

```
Traceback (most recent call last):  File "/Users/brennannovak/Mailpile Code/Mailpile/mailpile/httpd.py", line 351, in _real_do_GET    authenticate=(not mailpile.util.TESTING))  File "/Users/brennannovak/Mailpile Code/Mailpile/mailpile/urlmap.py", line 407, in map    fmt='json', async=is_async),  File "/Users/brennannovak/Mailpile Code/Mailpile/mailpile/urlmap.py", line 306, in _map_api_command    async=async)  File "/Users/brennannovak/Mailpile Code/Mailpile/mailpile/urlmap.py", line 123, in _command    raise BadDataError('Bad variable (%s): %s' % (var, name))BadDataError: Bad variable (gpg_email_key): setup/crypto
```

Seems like the `gpg_email_key` is no longer in the results / accepted by this endpoint.

**Comment by BjarniRunar** [comment]
This settings dialog is no longer in use. Thanks for filing!
