### ISSUE TITLE
Error while validating « security » dialog box

### ISSUE THREAD

**Issue by JocelynDelalande** [mailpile/Mailpile#1085]
If I hit « save changes » on `/setup/#security` view, the UI never responds, because, the backend raise the following exception : 
```
POST: /api/0/setup/crypto/ qs = {} post = {'encrypt_events': ['true'], 'encrypt_mail': ['true'], 
'index_encrypted': ['true'], 'encrypt_index': ['false'], 'gpg_email_key': ['false'], 'encrypt_misc': ['true'], 'passphrase_confirm': ['**********'], 'passphrase': ['****'], 'encrypt_vcards': ['true']}
Traceback (most recent call last):
  File "/home/jocelyn/Mailpile/mailpile/httpd.py", line 352, in _real_do_GET
    authenticate=(not mailpile.util.TESTING))
  File "/home/jocelyn/Mailpile/mailpile/urlmap.py", line 407, in map
    fmt='json', async=is_async),
  File "/home/jocelyn/Mailpile/mailpile/urlmap.py", line 306, in _map_api_command
    async=async)
  File "/home/jocelyn/Mailpile/mailpile/urlmap.py", line 123, in _command
    raise BadDataError('Bad variable (%s): %s' % (var, name))
BadDataError: Bad variable (gpg_email_key): setup/crypto
```

**Comment by BjarniRunar** [comment]
This is obsolete, that part of the setup flow and settings is gone. :-)
