### ISSUE TITLE
Tagging with a nonexistant tag, should not pretend it succeeded

### ISSUE THREAD

**Issue by JocelynDelalande** [mailpile/Mailpile#1096]
From CLI, I can do :

    tag +foo all

But then, if I search:
    s in:foo

I get an error:

```
Traceback (most recent call last):
  File "/home/jocelyn/Mailpile/mailpile/commands.py", line 558, in _run_sync
    return self._finishing(command, command(self, *args, **kwargs))
  File "/home/jocelyn/Mailpile/mailpile/commands.py", line 555, in command
    return self.command(*args, **kwargs)
  File "/home/jocelyn/Mailpile/mailpile/app.py", line 114, in command
    Interact(session)
  File "/home/jocelyn/Mailpile/mailpile/app.py", line 75, in Interact
    session.ui.display_result(Action(session, opt, arg))
  File "/home/jocelyn/Mailpile/mailpile/commands.py", line 2330, in Action
    return command(session, opt, arg, data=data).run()
  File "/home/jocelyn/Mailpile/mailpile/commands.py", line 601, in run
    return self._run(*args, **kwargs)
  File "/home/jocelyn/Mailpile/mailpile/commands.py", line 593, in _run
    return self._run_sync(True, *args, **kwargs)
  File "/home/jocelyn/Mailpile/mailpile/commands.py", line 530, in _run_sync
    self._starting()
  File "/home/jocelyn/Mailpile/mailpile/plugins/search.py", line 101, in _starting
    args += [a for a in list(nq(a) for a in self.args) if a not in args]
  File "/home/jocelyn/Mailpile/mailpile/plugins/search.py", line 101, in <genexpr>
    args += [a for a in list(nq(a) for a in self.args) if a not in args]
  File "/home/jocelyn/Mailpile/mailpile/plugins/search.py", line 95, in nq
    t = 'in:%s' % session.config.get_tag(t.split(':')[1]).slug
AttributeError: 'NoneType' object has no attribute 'slug'
```

Expected result of tagging with a new tag (eg: "foo") should be the creation of a new tag on the fly.

**Comment by BjarniRunar** [comment]
According to @rlindsgaard (at CCC) this one is fixed. :)

**Comment by JocelynDelalande** [comment]
I can confirm, thanks :)
