### ISSUE TITLE
Suggestion: do not download *all* historical email

### ISSUE THREAD

**Issue by hjwp** [mailpile/Mailpile#1098]
Just installed mailpile, loving the experience so far, very very impressed.

First problem encountered:  mailpile seems to be trying to download my full history of emails, going back almost ten years.  that's like 8 gigs of emails.  I don't really want them all on my hard disk just now.  Maybe offer an option to only download, eg 2 weeks or 1 month of history?

**Comment by BjarniRunar** [comment]
I think I'm going to say "this will never happen for POP", but it might still be possible for IMAP in some way. Updating tags to match.

**Comment by sirex** [comment]
I'm running Beta III (v0.5.2), I had to wait whole four days until all 71380 messages where downloaded (7.7G in total). As @hjwp pointed out, smartphones handle emails very well, after logging in I can instantly see new emails.

And now, even if all messages are downloaded, I still can't see latest messages, that I see in gmail. Mailpile says: `No new mail at 09:36`.

And another thing, one of my accounts magically disappeared.

And also, at some point there where no space left on my disk, Mailpile web ui continued to work, but command line interface was all covered with exceptions and did not responded to any key presses:

```
Exception in thread :
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/sirex/mailpile/mailpile/mail_source/__init__.py", line 875, in run
    self._log_status(_('Internal error!  Sleeping...'))
  File "/home/sirex/mailpile/mailpile/mail_source/__init__.py", line 167, in _log_status
    self.session.config.event_log.log_event(self.event)
  File "/home/sirex/mailpile/mailpile/eventlog.py", line 355, in log_event
    self._save_events([event])
  File "/home/sirex/mailpile/mailpile/eventlog.py", line 248, in _save_events
    self._open_log()
  File "/home/sirex/mailpile/mailpile/eventlog.py", line 220, in _open_log
    long_running=True)
  File "/home/sirex/mailpile/mailpile/crypto/streamer.py", line 494, in EncryptingStreamer
    return EncryptingUndelimitedStreamer(*args, **kwargs)
  File "/home/sirex/mailpile/mailpile/crypto/streamer.py", line 402, in __init__
    use_filter=use_filter)
  File "/home/sirex/mailpile/mailpile/crypto/streamer.py", line 261, in __init__
    self._write_preamble()
  File "/home/sirex/mailpile/mailpile/crypto/streamer.py", line 465, in _write_preamble
    self.fd.flush()
IOError: [Errno 28] No space left on device
```
