### ISSUE TITLE
Add UI "nagification" when SMTP connecting fails

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1100]
Currently, when there are outgoing messages in the Outbox but when SMTP connecting fails, the message just sits there. Looking at the CLI there is an error message like:

```
bg/log(10): Failed to send <mailpile.mailutils.Email object at 0x10e244b10>
bg/log(50): Traceback (most recent call last):
  File "/Users/brennannovak/Mailpile Code/Mailpile/mailpile/plugins/compose.py", line 856, in command
    events=events)])
  File "/Users/brennannovak/Mailpile Code/Mailpile/mailpile/smtp_client.py", line 325, in SendMail
    RunTimed(300, sm_startup)
  File "/Users/brennannovak/Mailpile Code/Mailpile/mailpile/util.py", line 714, in work
    result.append(func(*args, **kwargs))
  File "/Users/brennannovak/Mailpile Code/Mailpile/mailpile/smtp_client.py", line 269, in sm_startup
    server.connect(host, int(port))
  File "/Users/brennannovak/Mailpile Code/Mailpile/mailpile/smtp_client.py", line 94, in connect
    return cls.connect(self, host=host, port=port)
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/smtplib.py", line 309, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/Users/brennannovak/Mailpile Code/Mailpile/mailpile/smtp_client.py", line 83, in _get_socket
    new_socket.connect((host, port))
  File "/usr/local/Cellar/python/2.7.3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 60] Operation timed out

bg/log(10): sendmail error: Nothing was sent
```

But looking  at the `eventlog` there is an event that could be surfaced to the UI

```
{
  data: {
    auth: true,
    delivered: 0,
    host: "smtp.mailgun.org",
    mid: "10J1",
    proto: "smtp",
    recipients: 3,
    sid: "KxhpHAqm"
  },
  date: "Tue, 18 Nov 2014 11:48:30 -0000",
  event_id: "546b29b6.007a6.1238d",
  flags: "i",
  message: "Failed to send <mailpile.mailutils.Email object at 0x10e244350>",
  private_data: {
    hi@xxxxxx.com>hi@xxxxxx.com: false,
    hi@xxxxxx.com>jenny@xxxxxx.com: false,
    hi@xxxxxx.com>mia@xxxxxxx.com: false
  },
  source: ".plugins.compose.Sendit",
  ts: 1416311310.364094
}
``
```

**Comment by BjarniRunar** [comment]
I've got this done in my UI branch, will close when I merge.
