### ISSUE TITLE
Cookie Error when having some cookies set on localhost

### ISSUE THREAD

**Issue by Dignifiedquire** [mailpile/Mailpile#1151]
Hey, I just downloaded the beta from the homepage and tried to run it, but I'm getting the following issue

```
CookieError: Illegal key value: express:sess
```

I'm using Chrome `Version 39.0.2171.71 (64-bit)` on OS X 10.10.1. As far as I've determined your cookie parser doesn't seem to handle some types of cookies to well, see this [stackoverflow question](http://stackoverflow.com/questions/7148458/cookieerror-illegal-key-value).

Using an incognito window or deleting all cookies on localhost solves the issue.

## Full error output from `mailpile.py`

```bash
----------------------------------------

Mailpile.py          a tool                 Copyright 2013-2014, Mailpile ehf
               for searching and                   <https://www.mailpile.is/>
           organizing piles of e-mail

This program is free software: you can redistribute it and/or modify it under
the terms of either the GNU Affero General Public License as published by the
Free Software Foundation or the Apache License 2.0 as published by the Apache
Software Foundation. See the file COPYING.md for details.

The Web interface address is: http://localhost:33411/

   * Type `help` for instructions or `quit` to quit.
   * Long running operations can be aborted by pressing: <CTRL-C>
   * Check your web browser!

mailpile> ----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 58616)
Traceback (most recent call last):
  File "/Applications/Mailpile.app/Contents/Resources/Mailpile-Brew/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 595, in process_request_thread
    self.finish_request(request, client_address)
  File "/Applications/Mailpile.app/Contents/Resources/Mailpile/mailpile/httpd.py", line 424, in finish_request
    SimpleXMLRPCServer.finish_request(self, request, client_address)
  File "/Applications/Mailpile.app/Contents/Resources/Mailpile-Brew/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Applications/Mailpile.app/Contents/Resources/Mailpile-Brew/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 651, in __init__
    self.handle()
  File "/Applications/Mailpile.app/Contents/Resources/Mailpile-Brew/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/Applications/Mailpile.app/Contents/Resources/Mailpile-Brew/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/Applications/Mailpile.app/Contents/Resources/Mailpile/mailpile/httpd.py", line 271, in do_GET
    return self._real_do_GET(*args, **kwargs)
  File "/Applications/Mailpile.app/Contents/Resources/Mailpile/mailpile/httpd.py", line 318, in _real_do_GET
    'http_session': self.http_session(),
  File "/Applications/Mailpile.app/Contents/Resources/Mailpile/mailpile/httpd.py", line 84, in http_session
    cookies = Cookie.SimpleCookie(self.headers.get('cookie'))
  File "/Applications/Mailpile.app/Contents/Resources/Mailpile-Brew/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/Cookie.py", line 576, in __init__
    if input: self.load(input)
  File "/Applications/Mailpile.app/Contents/Resources/Mailpile-Brew/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/Cookie.py", line 629, in load
    self.__ParseString(rawdata)
  File "/Applications/Mailpile.app/Contents/Resources/Mailpile-Brew/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/Cookie.py", line 662, in __ParseString
    self.__set(K, rval, cval)
  File "/Applications/Mailpile.app/Contents/Resources/Mailpile-Brew/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/Cookie.py", line 582, in __set
    M.set(key, real_value, coded_value)
  File "/Applications/Mailpile.app/Contents/Resources/Mailpile-Brew/Cellar/python/2.7.8/Frameworks/Python.framework/Versions/2.7/lib/python2.7/Cookie.py", line 457, in set
    raise CookieError("Illegal key value: %s" % key)
CookieError: Illegal key value: express:sess
----------------------------------------
```

## Current cookies on localhost

```json
[
{
    "domain": "localhost",
    "hostOnly": true,
    "httpOnly": false,
    "name": "__profilin",
    "path": "/",
    "secure": false,
    "session": true,
    "storeId": "0",
    "value": "p%3Dt",
    "id": 1
},
{
    "domain": "localhost",
    "hostOnly": true,
    "httpOnly": true,
    "name": "_forum_session",
    "path": "/",
    "secure": false,
    "session": true,
    "storeId": "0",
    "value": "BAh7CkkiD3Nlc3Npb25faWQGOgZFVEkiJTYwNDZiOGYwMTE0YTE1ZDdkYWZkMDA1MjA1MWFjZDMyBjsAVEkiEF9jc3JmX3Rva2VuBjsARkkiMTNRV2hUdUFnOG4zVHhaTzN3K1pDRkF2bUdZdnVEOGpEWXBRZC94Nmg2bGc9BjsARkkiGXVzZXJfY3JlYXRlZF9tZXNzYWdlBjsAVEkiAgsBPHA%2BWW91J3JlIGFsbW9zdCBkb25lISBXZSBzZW50IGFuIGFjdGl2YXRpb24gbWFpbCB0byA8Yj5kaWduaWZpZWRxdWlyZUBnbWFpbC5jb208L2I%2BLiBQbGVhc2UgZm9sbG93IHRoZSBpbnN0cnVjdGlvbnMgaW4gdGhlIGVtYWlsIHRvIGFjdGl2YXRlIHlvdXIgYWNjb3VudC48L3A%2BPHA%2BSWYgaXQgZG9lc24ndCBhcnJpdmUsIGNoZWNrIHlvdXIgc3BhbSBmb2xkZXIsIG9yIHRyeSB0byBsb2cgaW4gYWdhaW4gdG8gc2VuZCBhbm90aGVyIGFjdGl2YXRpb24gbWFpbC48L3A%2BBjsAVEkiGmRpc2FibGVfY3VzdG9taXphdGlvbgY7AEZGSSIKZmxhc2gGOwBUewdJIgxkaXNjYXJkBjsAVFsASSIMZmxhc2hlcwY7AFR7BkkiDHJlZmVyZXIGOwBUIjVodHRwOi8vbG9jYWxob3N0OjMwMDAvdC93ZWxjb21lLXRvLWRpc2NvdXJzZS84LzE%3D--5ff8bf636580d2b512fa15b8c6e1744164951849",
    "id": 2
},
{
    "domain": "localhost",
    "hostOnly": true,
    "httpOnly": true,
    "name": "_scend_key",
    "path": "/",
    "secure": false,
    "session": true,
    "storeId": "0",
    "value": "g3QAAAABZAAQcGhvZW5peF9tZXNzYWdlc3QAAAAA--AF89AA454CB955196CA8C6420242A864EB40298",
    "id": 3
},
{
    "domain": "localhost",
    "expirationDate": 2047107551,
    "hostOnly": true,
    "httpOnly": true,
    "name": "_t",
    "path": "/",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "69c8748c0f84b9679aaf641910d54263",
    "id": 4
},
{
    "domain": "localhost",
    "hostOnly": true,
    "httpOnly": false,
    "name": "auth",
    "path": "/",
    "secure": false,
    "session": true,
    "storeId": "0",
    "value": "Z3Vlc3Q6Z3Vlc3Q%3D",
    "id": 5
},
{
    "domain": "localhost",
    "hostOnly": true,
    "httpOnly": true,
    "name": "connect.sid",
    "path": "/",
    "secure": false,
    "session": true,
    "storeId": "0",
    "value": "s%3AEFVg3yv1ESI5mdK3GBj2piBK.CfhmFz%2BfZqqCYz%2BgFdNnUJMR5Ih42dXDLdm8qesF3%2Fk",
    "id": 6
},
{
    "domain": "localhost",
    "hostOnly": true,
    "httpOnly": true,
    "name": "express:sess",
    "path": "/",
    "secure": false,
    "session": true,
    "storeId": "0",
    "value": "eyJwYXNzcG9ydCI6eyJ1c2VyIjoiZGlnbmlmaWVkcXVpcmVAZ21haWwuY29tIn19",
    "id": 7
},
{
    "domain": "localhost",
    "hostOnly": true,
    "httpOnly": true,
    "name": "express:sess.sig",
    "path": "/",
    "secure": false,
    "session": true,
    "storeId": "0",
    "value": "rV2oaXM2EI972BI6DE0DgOpX3ws",
    "id": 8
},
{
    "domain": "localhost",
    "expirationDate": 1436454393,
    "hostOnly": true,
    "httpOnly": false,
    "name": "m",
    "path": "/",
    "secure": false,
    "session": false,
    "storeId": "0",
    "value": "34e2:|18c3:t",
    "id": 9
},
{
    "domain": "localhost",
    "hostOnly": true,
    "httpOnly": false,
    "name": "PRUM_EPISODES",
    "path": "/",
    "secure": false,
    "session": true,
    "storeId": "0",
    "value": "s=1403177675975&r=http%3A//localhost%3A3000/topic/standard-builtins-prototypes-and-tostring",
    "id": 10
}
]
```

**Comment by BjarniRunar** [comment]
Neat! Thanks for reporting this, I'll see what I can do.

**Comment by BjarniRunar** [comment]
Should be fixed, please re-open if not!
