### ISSUE TITLE
I always get the issue "invalid syntax" when i start mp.

### ISSUE THREAD

**Issue by MoritzFago** [mailpile/Mailpile#1179]
I am working on an [Uberspace](https://www.uberspace.de), it´s shared hosting. I only run ```pip install -r requirements.txt``` for setup, this is the trace: 
```
Traceback (most recent call last):
  File "./mp", line 10, in <module>
    from mailpile.app import Main
  File "/[HOMEDIR]/lib/python2.6/mailpile-0.4.0.dev20150102-py2.6.egg/mailpile/__init__.py", line 1, in <module>
    import mailpile.app
  File "/[HOMEDIR]/lib/python2.6/mailpile-0.4.0.dev20150102-py2.6.egg/mailpile/app.py", line 8, in <module>
    import mailpile.defaults
  File "/[HOMEDIR]/lib/python2.6/mailpile-0.4.0.dev20150102-py2.6.egg/mailpile/defaults.py", line 16, in <module>
    from mailpile.config import PathDict
  File "/[HOMEDIR]/lib/python2.6/mailpile-0.4.0.dev20150102-py2.6.egg/mailpile/config.py", line 18, in <module>
    from mailpile.command_cache import CommandCache
  File "/[HOMEDIR]/lib/python2.6/mailpile-0.4.0.dev20150102-py2.6.egg/mailpile/command_cache.py", line 8, in <module>
    from mailpile.ui import Session, BackgroundInteraction
  File "/[HOMEDIR]/lib/python2.6/mailpile-0.4.0.dev20150102-py2.6.egg/mailpile/ui.py", line 27, in <module>
    import mailpile.commands
  File "/[HOMEDIR]/lib/python2.6/mailpile-0.4.0.dev20150102-py2.6.egg/mailpile/commands.py", line 1784
    with BLOCK_HTTPD_LOCK, Idle_HTTPD():
                         ^
```

**Comment by maxfell** [comment]
Can you check what python version you are running? (type `python -V` in your command line). For me this issue occurred because I wasn't using Python 2.7.

**Comment by ClashTheBunny** [comment]
Every other line of the stacktrace includes "python2.6" in the path, so the solution is the solution to #789.

**Comment by BjarniRunar** [comment]
Yep, we're Python 2.7 only at the moment. See #160 for one proposed change to that. ;-)

Nobody's filed a bug for supporting *older* Pythons yet.
