### ISSUE TITLE
Error message on opening index

### ISSUE THREAD

**Issue by daniel-sousa-me** [mailpile/Mailpile#1236]
When I run "load" on the Mailpile console I get the following error:

Traceback (most recent call last):
  File "/home/daniel/Mailpile/mailpile/commands.py", line 564, in _run_sync
    return self._finishing(command(self, *args, **kwargs))
  File "/home/daniel/Mailpile/mailpile/commands.py", line 562, in command
    return self.command(*args, **kwargs)
  File "/home/daniel/Mailpile/mailpile/commands.py", line 1118, in command
    quiet=quiet):
  File "/home/daniel/Mailpile/mailpile/commands.py", line 325, in _idx
    rv = __do_load1()
  File "/home/daniel/Mailpile/mailpile/commands.py", line 317, in __do_load1
    idx = config.get_index(session)
  File "/home/daniel/Mailpile/mailpile/config.py", line 1900, in get_index
    self.index_check.release()
error: release unlocked lock

The web interface "Internal error! Sleeping..." on the Mail Sources page

**Comment by daniel-sousa-me** [comment]
It magically started working
