### ISSUE TITLE
Mailpile hangs during "Create your passphrase"

### ISSUE THREAD

**Issue by hdfssk** [mailpile/Mailpile#1245]
When running mailpile for the first time (on a machine w/ no PGP keys installed),  a *Create your passphrase* window opens. After filling in both form fields (with “`This is my test passphrase.`”) and clicking ‘Authenticate’, everything on the page disappears except the #identity-vault-lock div:
![shot feb 11 2015 7 17 36pm](https://cloud.githubusercontent.com/assets/8379226/6159403/fe76f75a-b222-11e4-88f1-ab0621f9bada.jpeg)
The page hangs like this indefinitely. Relaunching mailpile or reloading the page takes me back to *Create your passphrase* w/ two top secret super duper p/w fields.

Running `set sys,debug = log` and `eventlog/watch` before clicking ‘Authenticate’ produces this:
```
Watching logs: Press CTRL-C to return to the CLI
bg/log(20): http/log(20): Elapsed: 0.000s (output: Set output mode to: json)
54dbed63.00010.4456=SetupCrypto:R setup/crypto: Starting
bg/log(50): http/log(50): Logged in qXziDw0XhsC6n6GTTr8Mj2T1Gvk as DEFAULT
bg/log(50): http/log(50): Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mailpile/commands.py", line 564, in _run_sync
    return self._finishing(command(self, *args, **kwargs))
  File "/usr/lib/python2.7/site-packages/mailpile/commands.py", line 562, in command
    return self.command(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mailpile/plugins/setup_magic.py", line 365, in command
    return self.setup_command(session, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mailpile/plugins/setup_magic.py", line 662, in setup_command
    session.config.prefs.gpg_recipient = choose_key
  File "/usr/lib/python2.7/site-packages/mailpile/config.py", line 805, in __setattr__
    self.__setitem__(attr, value)
  File "/usr/lib/python2.7/site-packages/mailpile/config.py", line 851, in __setitem__
    ) % (self._name, key, value))
ValueError: Invalid value for config/prefs/gpg_recipient: !CREATE

bg/log(10): http/log(10): setup/crypto error: Failed: setup/crypto 
54dbed63.00010.4456=SetupCrypto:c setup/crypto: Failed: setup/crypto 
bg/log(20): http/log(20): Elapsed: 0.016s (setup/crypto: Failed: setup/crypto )
bg/log(20): http://localhost:33411 "POST /api/0/setup/crypto/ HTTP/1.1" 200 452
bg/log(40): Starting: refresh_command_cache
```

The POST I’m sending to http://localhost:33411/api/0/setup/crypto/:
```
choose_key	!CREATE
passphrase	This is my test passphrase.
passphrase_confirm	This is my test passphrase.
```
…and its response:
```
POST 
{
 "command": "setup/crypto", 
 "elapsed": "0.016", 
 "event_id": "54dbed63.00010.4456", 
 "message": "Failed: setup/crypto ", 
 "result": false, 
 "state": {
  "cache_id": "", 
  "command_url": "/setup/crypto/", 
  "context": "", 
  "context_url": "/setup/crypto/", 
  "query_args": {
   "_method": "POST", 
   "choose_key": [
    "!CREATE"
   ], 
   "passphrase": "(SUPPRESSED)", 
   "passphrase_confirm": "(SUPPRESSED)"
  }
 }, 
 "status": "error"
}
```

My browser’s javascript console shows this error afterwards:
```
TypeError: result.error is undefined
setup.js (line 159)
else if (result.status == 'error' && result.error.invalid_passphrase) {
```

**Comment by BjarniRunar** [comment]
This has already been fixed in HEAD (commit da2e39ba4d45846cb5cb5b9e1060948e29eafb2b).

Where did you download Mailpile from? And when?

**Comment by pingswept** [comment]
I experienced this using the 0.4.3 release, but not with 0.4.2. Given that it's fixed in HEAD, I wouldn't worry about it too much, Maybe a 0.4.4 release, or just carry on?

**Comment by rigelk** [comment]
same as @pingswept using the 0.4.3 release.
