### ISSUE TITLE
Empty parts list when converting path to tagname, raises exception

### ISSUE THREAD

**Issue by whummer** [mailpile/Mailpile#1246]
I ran into an internal error when importing mail from an IMAP server, problem was caused by method _path_to_tagname in file mailpile/mail_source/__init__.py . The parts list was empty, hence pop(-1) results in an exception. 

```
Traceback (most recent call last):
  File "mailpile/mailpile/mail_source/__init__.py", line 754, in run
    self.sync_mail()
  File "mailpile/mailpile/mail_source/__init__.py", line 180, in sync_mail
    stop_after=batch)
  File "mailpile/mailpile/mail_source/__init__.py", line 648, in rescan_mailbox
    self._create_primary_tag(mbx_cfg)
  File "mailpile/mailpile/mail_source/__init__.py", line 428, in _create_primary_tag
    mbx_cfg.primary_tag = self._create_tag_name(self._path(mbx_cfg))
  File "mailpile/mailpile/mail_source/__init__.py", line 484, in _create_tag_name
    return self._unique_tag_name(self._path_to_tagname(path))
  File "mailpile/mailpile/mail_source/__init__.py", line 469, in _path_to_tagname
    tagname = parts.pop(-1).split('.')[0]
```

The following changes (3 lines) fixed the problem for me. (I did not investigate the reason further, and did not check which other side effects this has, though)

```
def _path_to_tagname(self, path):  # -> tag name
        """This converts a path to a tag name."""
        path = self._mailbox_name(path).replace('/.', '/')
        parts = ('/' in path) and path.split('/') or path.split('\\')
        parts = [p for p in parts if not re.match(self.BORING_FOLDER_RE, p)]
        tagname = ""   # changed
        if len(parts) > 0:   # changed
                tagname = parts.pop(-1).split('.')[0]   # changed
        return re.sub(self.TAGNAME_STRIP_RE, '', tagname.replace('_', ' '))
```

**Comment by BjarniRunar** [comment]
Is this from the beta, beta II, or HEAD?

**Comment by whummer** [comment]
Sorry, forgot to mention, tested from HEAD. (commit 736c019a0d14e1e0c289db13a9668d008c6fa7c7)
