### ISSUE TITLE
Mailpile needs to treat file-system paths as binary data

### ISSUE THREAD

**Issue by rysiekpl** [mailpile/Mailpile#1249]
When adding a Maildir mail source to MailPile, if the Maildir source contains paths with Unicode characters in them, MailPile fails with an "Internal Error". Inspecting `eventlog` shows:

```
Traceback (most recent call last):
  File "/Mailpile/mailpile/mail_source/__init__.py", line 753, in run
    self.sync_mail()
  File "/Mailpile/mailpile/mail_source/__init__.py", line 223, in sync_mail
    discovered = self.discover_mailboxes()
  File "/Mailpile/mailpile/mail_source/__init__.py", line 317, in discover_mailboxes
    mbx_cfg = self.take_over_mailbox(mailbox_idx, save=False)
  File "/Mailpile/mailpile/mail_source/__init__.py", line 340, in take_over_mailbox
    mbx_cfg.name = self._mailbox_name(self._path(mbx_cfg))
  File "/Mailpile/mailpile/config.py", line 836, in __setattr__
    self.__setitem__(attr, value)
  File "/Mailpile/mailpile/config.py", line 882, in __setitem__
    ) % (self._name, key, value))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 5: ordinal not in range(128)
```

Offending character is in this case "ż", this probably is not very important.

**Comment by BjarniRunar** [comment]
Thanks for filing! This problem is actually deep and far reaching within the app.

The issue is that filesystem paths need to be treated as binary data, but there are multiple places where they are treated instead as unicode strings, including in the JSON representations used by the web API itself. So this is a problem all the way from the app config, to the filesystem code, to the API, to the user interface itself when displaying paths to a user.

The representation in the app config has been fixed to handle binary data (efb8c4eaf90bcbcfd56e58e9cf614e3c0f7d7bdc), but the problem still persists in quite a few other places.

**Comment by BjarniRunar** [comment]
Note: Fixing this may take a long time. For now the workaround is to rename paths or use symbolic links that do not contain non-utf-8 character encodings.

**Comment by llange** [comment]
Hello,
I'm also hit by this. Unfortunately symlinking is not an option, as the utf-8 characters occur in the names of the files (Maildir mailbox) - that would mean symlinking in realtime each and every file in Maildir.

```
mailpile> WARNING: 000d1523104967.86086_6.S%CC%8Cnek%2CU%3D7179 not found
Traceback (most recent call last):
  File "/Mailpile/mailpile/index/base.py", line 121, in enumerate_ptrs_mboxes_fds
    fd = mbox.get_file_by_ptr(msg_ptr)
  File "/Mailpile/mailpile/mailboxes/__init__.py", line 162, in get_file_by_ptr
    return self.get_file(unquote(msg_ptr[MBX_ID_LEN:]))
  File "/Mailpile/mailpile/mailboxes/__init__.py", line 159, in get_file
    return parent.get_file(self, *args, **kwargs)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/mailbox.py", line 378, in get_file
    f = open(os.path.join(self._path, self._lookup(key)), 'rb')
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/mailbox.py", line 548, in _lookup
    raise KeyError('No message with key: %s' % key)
KeyError: u'No message with key: 1523104967.86086_6.S\xcc\x8cnek,U=7179'
```
I managed +/- to reproduce the issue with:
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import mailbox
from urllib import quote, unquote

inbox = mailbox.Maildir('/tmp/mypath', factory=None, create=False)
for key in inbox.iterkeys():
    print "%s / %r" % (key, key)
    file = inbox.get_file(unquote(unicode(quote(key))))
```

```
1523104967.86086_6.Šnek,U=7179 / '1523104967.86086_6.S\xcc\x8cnek,U=7179'
Traceback (most recent call last):
  File "debug.py", line 27, in <module>
    file = inbox.get_file(unquote(unicode(quote(key))))
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/mailbox.py", line 378, in get_file
    f = open(os.path.join(self._path, self._lookup(key)), 'rb')
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/mailbox.py", line 548, in _lookup
    raise KeyError('No message with key: %s' % key)
KeyError: u'No message with key: 1523104967.86086_6.S\xcc\x8cnek,U=7179'
```

I'd like to help fixing this, is there any starting point that I could use ?

**Comment by BjarniRunar** [comment]
I'm afraid this is one of those issues where by the time I've figured out how to advise you on where to start, I'll probably have figured out how to fix it.

I'm taking a look now. Your test case above is really useful by the way, thanks for that!
