### ISSUE TITLE
Mailpile build broken: ImportError: cannot import name TemplatesNotFound

### ISSUE THREAD

**Issue by steowens** [mailpile/Mailpile#1250]
Steps to reproduce:

```
[root@mail src]# git clone https://github.com/mailpile/Mailpile.git
git: /usr/local/lib/libz.so.1: no version information available (required by git)
Initialized empty Git repository in /usr/src/Mailpile/.git/
git-remote-https: /usr/local/lib/libz.so.1: no version information available (required by git-remote-https)
git: /usr/local/lib/libz.so.1: no version information available (required by git)
remote: Counting objects: 30535, done.
remote: Compressing objects: 100% (63/63), done.
git: /usr/local/lib/libz.so.1: no version information available (required by git)
remote: Total 30535 (delta 38), reused 3 (delta 0)
Receiving objects: 100% (30535/30535), 16.71 MiB | 6.74 MiB/s, done.
Resolving deltas: 100% (20098/20098), done.
[root@mail src]# yum install gnupg openssl python-devel libxml2-devel libxslt-devel zlibrary-devel python-jinja2 python3-jinja2 python-lxml python3-lxml python-pgpdump python3-pgpdump
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: repos.lax.quadranet.com
 * epel: mirror.prgmr.com
 * extras: repos.lax.quadranet.com
 * ius: mirror.symnds.com
 * updates: repos.lax.quadranet.com
Package gnupg2-2.0.14-8.el6.x86_64 already installed and latest version
Package openssl-1.0.1e-30.el6_6.5.x86_64 already installed and latest version
No package python3-jinja2 available.
No package python3-lxml available.
No package python3-pgpdump available.
Resolving Dependencies
--> Running transaction check
---> Package libxml2-devel.x86_64 0:2.7.6-17.el6_6.1 will be installed
---> Package libxslt-devel.x86_64 0:1.1.26-2.el6_3.1 will be installed
--> Processing Dependency: libxslt = 1.1.26-2.el6_3.1 for package: libxslt-devel-1.1.26-2.el6_3.1.x86_64
--> Processing Dependency: libgcrypt-devel for package: libxslt-devel-1.1.26-2.el6_3.1.x86_64
--> Processing Dependency: libxslt.so.1()(64bit) for package: libxslt-devel-1.1.26-2.el6_3.1.x86_64
--> Processing Dependency: libexslt.so.0()(64bit) for package: libxslt-devel-1.1.26-2.el6_3.1.x86_64
---> Package python-devel.x86_64 0:2.6.6-52.el6 will be installed
---> Package python-jinja2.x86_64 0:2.2.1-2.el6_5 will be installed
--> Processing Dependency: python-babel >= 0.8 for package: python-jinja2-2.2.1-2.el6_5.x86_64
---> Package python-lxml.x86_64 0:2.2.3-1.1.el6 will be installed
---> Package python-pgpdump.noarch 0:1.4-2.el6 will be installed
---> Package zlibrary-devel.x86_64 0:0.12.10-5.el6 will be installed
--> Processing Dependency: zlibrary = 0.12.10-5.el6 for package: zlibrary-devel-0.12.10-5.el6.x86_64
--> Processing Dependency: libzltext.so.0.13()(64bit) for package: zlibrary-devel-0.12.10-5.el6.x86_64
--> Processing Dependency: libzlcore.so.0.13()(64bit) for package: zlibrary-devel-0.12.10-5.el6.x86_64
--> Running transaction check
---> Package libgcrypt-devel.x86_64 0:1.4.5-11.el6_4 will be installed
--> Processing Dependency: libgpg-error-devel for package: libgcrypt-devel-1.4.5-11.el6_4.x86_64
---> Package libxslt.x86_64 0:1.1.26-2.el6_3.1 will be installed
---> Package python-babel.noarch 0:0.9.4-5.1.el6 will be installed
---> Package zlibrary.x86_64 0:0.12.10-5.el6 will be installed
--> Processing Dependency: zlibrary-ui = 0.12.10-5.el6 for package: zlibrary-0.12.10-5.el6.x86_64
--> Processing Dependency: liblinebreak.so.2()(64bit) for package: zlibrary-0.12.10-5.el6.x86_64
--> Processing Dependency: libfribidi.so.0()(64bit) for package: zlibrary-0.12.10-5.el6.x86_64
--> Running transaction check
---> Package fribidi.x86_64 0:0.19.2-2.el6 will be installed
---> Package libgpg-error-devel.x86_64 0:1.7-4.el6 will be installed
---> Package liblinebreak.x86_64 0:2.1-1.el6 will be installed
---> Package zlibrary-ui-gtk.x86_64 0:0.12.10-5.el6 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

=========================================================================================================================================================================================================
 Package                                               Arch                                      Version                                                Repository                                  Size
=========================================================================================================================================================================================================
Installing:
 libxml2-devel                                         x86_64                                    2.7.6-17.el6_6.1                                       updates                                    1.1 M
 libxslt-devel                                         x86_64                                    1.1.26-2.el6_3.1                                       base                                       561 k
 python-devel                                          x86_64                                    2.6.6-52.el6                                           base                                       171 k
 python-jinja2                                         x86_64                                    2.2.1-2.el6_5                                          base                                       466 k
 python-lxml                                           x86_64                                    2.2.3-1.1.el6                                          base                                       2.0 M
 python-pgpdump                                        noarch                                    1.4-2.el6                                              epel                                        38 k
 zlibrary-devel                                        x86_64                                    0.12.10-5.el6                                          epel                                        50 k
Installing for dependencies:
 fribidi                                               x86_64                                    0.19.2-2.el6                                           epel                                        50 k
 libgcrypt-devel                                       x86_64                                    1.4.5-11.el6_4                                         base                                       118 k
 libgpg-error-devel                                    x86_64                                    1.7-4.el6                                              base                                        14 k
 liblinebreak                                          x86_64                                    2.1-1.el6                                              epel                                        19 k
 libxslt                                               x86_64                                    1.1.26-2.el6_3.1                                       base                                       452 k
 python-babel                                          noarch                                    0.9.4-5.1.el6                                          base                                       1.4 M
 zlibrary                                              x86_64                                    0.12.10-5.el6                                          epel                                       1.1 M
 zlibrary-ui-gtk                                       x86_64                                    0.12.10-5.el6                                          epel                                        72 k

Transaction Summary
=========================================================================================================================================================================================================
Install      15 Package(s)

Total download size: 7.6 M
Installed size: 47 M
Is this ok [y/N]: y
Downloading Packages:
(1/15): fribidi-0.19.2-2.el6.x86_64.rpm                                                                                                                                           |  50 kB     00:00     
(2/15): libgcrypt-devel-1.4.5-11.el6_4.x86_64.rpm                                                                                                                                 | 118 kB     00:00     
(3/15): libgpg-error-devel-1.7-4.el6.x86_64.rpm                                                                                                                                   |  14 kB     00:00     
(4/15): liblinebreak-2.1-1.el6.x86_64.rpm                                                                                                                                         |  19 kB     00:00     
(5/15): libxml2-devel-2.7.6-17.el6_6.1.x86_64.rpm                                                                                                                                 | 1.1 MB     00:00     
(6/15): libxslt-1.1.26-2.el6_3.1.x86_64.rpm                                                                                                                                       | 452 kB     00:00     
(7/15): libxslt-devel-1.1.26-2.el6_3.1.x86_64.rpm                                                                                                                                 | 561 kB     00:00     
(8/15): python-babel-0.9.4-5.1.el6.noarch.rpm                                                                                                                                     | 1.4 MB     00:00     
(9/15): python-devel-2.6.6-52.el6.x86_64.rpm                                                                                                                                      | 171 kB     00:00     
(10/15): python-jinja2-2.2.1-2.el6_5.x86_64.rpm                                                                                                                                   | 466 kB     00:00     
(11/15): python-lxml-2.2.3-1.1.el6.x86_64.rpm                                                                                                                                     | 2.0 MB     00:00     
(12/15): python-pgpdump-1.4-2.el6.noarch.rpm                                                                                                                                      |  38 kB     00:00     
(13/15): zlibrary-0.12.10-5.el6.x86_64.rpm                                                                                                                                        | 1.1 MB     00:00     
(14/15): zlibrary-devel-0.12.10-5.el6.x86_64.rpm                                                                                                                                  |  50 kB     00:00     
(15/15): zlibrary-ui-gtk-0.12.10-5.el6.x86_64.rpm                                                                                                                                 |  72 kB     00:00     
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                    2.3 MB/s | 7.6 MB     00:03     
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : libxslt-1.1.26-2.el6_3.1.x86_64                                                                                                                                                      1/15 
  Installing : liblinebreak-2.1-1.el6.x86_64                                                                                                                                                        2/15 
  Installing : libxml2-devel-2.7.6-17.el6_6.1.x86_64                                                                                                                                                3/15 
  Installing : fribidi-0.19.2-2.el6.x86_64                                                                                                                                                          4/15 
  Installing : zlibrary-ui-gtk-0.12.10-5.el6.x86_64                                                                                                                                                 5/15 
  Installing : zlibrary-0.12.10-5.el6.x86_64                                                                                                                                                        6/15 
  Installing : libgpg-error-devel-1.7-4.el6.x86_64                                                                                                                                                  7/15 
  Installing : libgcrypt-devel-1.4.5-11.el6_4.x86_64                                                                                                                                                8/15 
  Installing : python-babel-0.9.4-5.1.el6.noarch                                                                                                                                                    9/15 
  Installing : python-jinja2-2.2.1-2.el6_5.x86_64                                                                                                                                                  10/15 
  Installing : libxslt-devel-1.1.26-2.el6_3.1.x86_64                                                                                                                                               11/15 
  Installing : zlibrary-devel-0.12.10-5.el6.x86_64                                                                                                                                                 12/15 
  Installing : python-lxml-2.2.3-1.1.el6.x86_64                                                                                                                                                    13/15 
  Installing : python-devel-2.6.6-52.el6.x86_64                                                                                                                                                    14/15 
  Installing : python-pgpdump-1.4-2.el6.noarch                                                                                                                                                     15/15 
  Verifying  : libgcrypt-devel-1.4.5-11.el6_4.x86_64                                                                                                                                                1/15 
  Verifying  : python-babel-0.9.4-5.1.el6.noarch                                                                                                                                                    2/15 
  Verifying  : libgpg-error-devel-1.7-4.el6.x86_64                                                                                                                                                  3/15 
  Verifying  : fribidi-0.19.2-2.el6.x86_64                                                                                                                                                          4/15 
  Verifying  : libxml2-devel-2.7.6-17.el6_6.1.x86_64                                                                                                                                                5/15 
  Verifying  : zlibrary-0.12.10-5.el6.x86_64                                                                                                                                                        6/15 
  Verifying  : python-pgpdump-1.4-2.el6.noarch                                                                                                                                                      7/15 
  Verifying  : python-devel-2.6.6-52.el6.x86_64                                                                                                                                                     8/15 
  Verifying  : python-jinja2-2.2.1-2.el6_5.x86_64                                                                                                                                                   9/15 
  Verifying  : liblinebreak-2.1-1.el6.x86_64                                                                                                                                                       10/15 
  Verifying  : python-lxml-2.2.3-1.1.el6.x86_64                                                                                                                                                    11/15 
  Verifying  : libxslt-devel-1.1.26-2.el6_3.1.x86_64                                                                                                                                               12/15 
  Verifying  : libxslt-1.1.26-2.el6_3.1.x86_64                                                                                                                                                     13/15 
  Verifying  : zlibrary-ui-gtk-0.12.10-5.el6.x86_64                                                                                                                                                14/15 
  Verifying  : zlibrary-devel-0.12.10-5.el6.x86_64                                                                                                                                                 15/15 

Installed:
  libxml2-devel.x86_64 0:2.7.6-17.el6_6.1   libxslt-devel.x86_64 0:1.1.26-2.el6_3.1   python-devel.x86_64 0:2.6.6-52.el6   python-jinja2.x86_64 0:2.2.1-2.el6_5   python-lxml.x86_64 0:2.2.3-1.1.el6  
  python-pgpdump.noarch 0:1.4-2.el6         zlibrary-devel.x86_64 0:0.12.10-5.el6    

Dependency Installed:
  fribidi.x86_64 0:0.19.2-2.el6          libgcrypt-devel.x86_64 0:1.4.5-11.el6_4    libgpg-error-devel.x86_64 0:1.7-4.el6     liblinebreak.x86_64 0:2.1-1.el6    libxslt.x86_64 0:1.1.26-2.el6_3.1   
  python-babel.noarch 0:0.9.4-5.1.el6    zlibrary.x86_64 0:0.12.10-5.el6            zlibrary-ui-gtk.x86_64 0:0.12.10-5.el6   

Complete!
[root@mail src]# ls
debug  kernels  Mailpile  node-v0.12.0  node-v0.12.0.tar.gz
[root@mail src]# cd Mailpile/
[root@mail Mailpile]# ls
AGPLv3.txt  COPYING.md     doc               fig.yml       LICENSE-2.0.txt  Makefile       mp            packages              requirements.txt  static
babel.cfg   default-theme  Dockerfile        Gruntfile.js  locale           MANIFEST.in    mp.cmd        README.md             scripts           testing-data
bower.json  design         external-plugins  indie.json    mailpile         MEM-STATS.TXT  package.json  requirements-dev.txt  setup.py          Vagrantfile
[root@mail Mailpile]# ./mp
Traceback (most recent call last):
  File "./mp", line 10, in <module>
    from mailpile.app import Main
  File "/usr/src/Mailpile/mailpile/__init__.py", line 1, in <module>
    import mailpile.app
  File "/usr/src/Mailpile/mailpile/app.py", line 8, in <module>
    import mailpile.defaults
  File "/usr/src/Mailpile/mailpile/defaults.py", line 16, in <module>
    from mailpile.config import PathDict
  File "/usr/src/Mailpile/mailpile/config.py", line 18, in <module>
    from mailpile.command_cache import CommandCache
  File "/usr/src/Mailpile/mailpile/command_cache.py", line 8, in <module>
    from mailpile.ui import Session, BackgroundInteraction
  File "/usr/src/Mailpile/mailpile/ui.py", line 25, in <module>
    from jinja2 import TemplatesNotFound, TemplateAssertionError, UndefinedError
ImportError: cannot import name TemplatesNotFound
[root@mail Mailpile]# 
```

**Comment by BjarniRunar** [comment]
Your jinja2 is too old, you'd need to install it using pip on this platform. This will be addressed when we start building our own proper RPM packages.

**Comment by steowens** [comment]
Ok thanks!
