### ISSUE TITLE
test failure: "keywords must be strings" under PyPy

### ISSUE THREAD

**Issue by bjmgeek** [mailpile/Mailpile#1257]
Running under a PyPy virtualenv, I got the following:
````
$ python -V
Python 2.7.8 (2.4.0+dfsg-2, Nov 27 2014, 21:36:13)
[PyPy 2.4.0 with GCC 4.9.2]
$ python setup.py test
running test
running egg_info
creating mailpile.egg-info
writing requirements to mailpile.egg-info/requires.txt
writing mailpile.egg-info/PKG-INFO
writing top-level names to mailpile.egg-info/top_level.txt
writing dependency_links to mailpile.egg-info/dependency_links.txt
writing entry points to mailpile.egg-info/entry_points.txt
writing manifest file 'mailpile.egg-info/SOURCES.txt'
reading manifest file 'mailpile.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*' found under directory 'locale'
warning: no previously-included files matching '*' found under directory 'scripts'
warning: no previously-included files matching '*' found under directory 'testing'
warning: no previously-included files matching '*~' found under directory 'mailpile/tests/data'
warning: no files found matching '*.mo' under directory 'mailpile/locale'
writing manifest file 'mailpile.egg-info/SOURCES.txt'
running build_ext
Failure: TypeError (keywords must be strings) ... ERROR

======================================================================
ERROR: Failure: TypeError (keywords must be strings)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/large_vol/home/bminton/public_html/programs/Mailpile/nose-1.3.4-py2.7.egg/nose/loader.py", line 414, in loadTestsFromName
    addr.filename, addr.module)
  File "/mnt/large_vol/home/bminton/public_html/programs/Mailpile/nose-1.3.4-py2.7.egg/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/mnt/large_vol/home/bminton/public_html/programs/Mailpile/nose-1.3.4-py2.7.egg/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/mnt/large_vol/home/bminton/public_html/programs/Mailpile/mailpile/__init__.py", line 1, in <module>
    import mailpile.app
  File "/mnt/large_vol/home/bminton/public_html/programs/Mailpile/mailpile/app.py", line 8, in <module>
    import mailpile.defaults
  File "/mnt/large_vol/home/bminton/public_html/programs/Mailpile/mailpile/defaults.py", line 16, in <module>
    from mailpile.config import PathDict
  File "/mnt/large_vol/home/bminton/public_html/programs/Mailpile/mailpile/config.py", line 18, in <module>
    from mailpile.command_cache import CommandCache
  File "/mnt/large_vol/home/bminton/public_html/programs/Mailpile/mailpile/command_cache.py", line 8, in <module>
    from mailpile.ui import Session, BackgroundInteraction
  File "/mnt/large_vol/home/bminton/public_html/programs/Mailpile/mailpile/ui.py", line 27, in <module>
    import mailpile.commands
  File "/mnt/large_vol/home/bminton/public_html/programs/Mailpile/mailpile/commands.py", line 33, in <module>
    from mailpile.search import MailIndex
  File "/mnt/large_vol/home/bminton/public_html/programs/Mailpile/mailpile/search.py", line 86, in <module>
    class MailIndex(object):
  File "/mnt/large_vol/home/bminton/public_html/programs/Mailpile/mailpile/search.py", line 143, in MailIndex
    0x7F: None
TypeError: keywords must be strings

----------------------------------------------------------------------
Ran 1 test in 0.497s

FAILED (errors=1)
````

**Comment by BjarniRunar** [comment]
PyPy isn't really a target environment. I'd accept pull requests to fix this sort of thing, but it's not an issue we'll address directly in the near future, so I'm closing this issue. Thanks for filing!
