### ISSUE TITLE
Generate GPG key

### ISSUE THREAD

**Issue by KLIM8D** [mailpile/Mailpile#1266]
Hi,

I am getting this error message while setting up Milepile on FreeBSD. I think it's related to GPG since it happens right after I've chosen my password and clicked the generate keys button.

```
Boo! GET_LINE keygen.algo not found in [GNUPG:] GET_LINE keygen.name
Traceback (most recent call last):
  File "/mnt/mail/Mailpile/mailpile/crypto/gpgi.py", line 1115, in run
    self.run_script, self.main_script)
  File "/mnt/mail/Mailpile/mailpile/crypto/gpgi.py", line 904, in chat
    return callback(proc, *args, **kwargs)
  File "/mnt/mail/Mailpile/mailpile/crypto/gpgi.py", line 1102, in run_script
    self.expect_exact(proc, exp, timeout=tmo)
  File "/mnt/mail/Mailpile/mailpile/crypto/gpgi.py", line 1091, in expect_exact
    if RunTimed(timeout, self._expecter, proc, exp, timebox):
  File "/mnt/mail/Mailpile/mailpile/util.py", line 718, in RunTimed
    RunTimedThread(func.__name__, work).run_timed(timeout)
  File "/mnt/mail/Mailpile/mailpile/util.py", line 707, in run_timed
    raise TimedOut('Timed out: %s' % self.name)
TimedOut: Timed out: _expecter
```

```
gpg (GnuPG) 2.1.2
libgcrypt 1.6.3
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: ~/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

**Comment by Kurmaev** [comment]
@KLIM8D, just try downgrade gnupg to 1.4.19 . Looks like mailpile doesn't support gnupg v2 yet

**Comment by KLIM8D** [comment]
@Kurmaev Yes that solves the issue, thanks
