### ISSUE TITLE
Web interface doesnt go past authentication screen

### ISSUE THREAD

**Issue by sbourke** [mailpile/Mailpile#1274]
I just did a git clone on mail pile. Got the command line interface up and running. When I goto http://localhost:33411 I'm presented with a create passphrae page. When I enter something I get the following error in my terminal (When I turn logging on). I'm on a mac yosemite.

    http/log(50): Traceback (most recent call last):
    File "/Users/steve/dev/code/Mailpile/mailpile/commands.py", line 560, in _run_sync
      return self._finishing(command(self, *args, **kwargs))
    File "/Users/steve/dev/code/Mailpile/mailpile/commands.py", line 558, in command
      return self.command(*args, **kwargs)
    File "/Users/steve/dev/code/Mailpile/mailpile/plugins/setup_magic.py", line 384, in command
      return self.setup_command(session, *args, **kwargs)
    File "/Users/steve/dev/code/Mailpile/mailpile/plugins/setup_magic.py", line 627, in setup_command
      'secret_keys': self.list_secret_keys(),
    File "/Users/steve/dev/code/Mailpile/mailpile/plugins/setup_magic.py", line 555, in list_secret_keys
      for key, details in self._gnupg().list_secret_keys().iteritems():
    File "/Users/steve/dev/code/Mailpile/mailpile/crypto/gpgi.py", line 613, in list_secret_keys
      retvals = self.run(list_keys)
    File "/Users/steve/dev/code/Mailpile/mailpile/crypto/gpgi.py", line 488, in run
      proc = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE, bufsize=0)
    File "/Users/steve/dev/code/Mailpile/mailpile/safe_popen.py", line 153, in __init__
      creationflags=creationflags)
    File "/Users/steve/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
      errread, errwrite)
    File "/Users/steve/anaconda/lib/python2.7/subprocess.py", line 1327, in _execute_child
      raise child_exception
    OSError: [Errno 2] No such file or directory

**Comment by BjarniRunar** [comment]
Looks like Mailpile can't find your gpg binary...?

**Comment by sbourke** [comment]
You are fully correct. Sorry!
