### ISSUE TITLE
running help/variables returns a python error

### ISSUE THREAD

**Issue by maysara** [mailpile/Mailpile#1307]
while trying to figure out how to debug imap connectivity/authentication issues, i ran help help and then help/variables as suggested by help help; the output is as follows:

mailpile> help/variables
Traceback (most recent call last):
  File "/home/.../code/Mailpile/mailpile/commands.py", line 583, in _run_sync
    return self._finishing(command(self, *args, **kwargs))
  File "/home/.../code/Mailpile/mailpile/commands.py", line 581, in command
    return self.command(*args, **kwargs)
  File "/home/.../code/Mailpile/mailpile/commands.py", line 2538, in command
    what = config[cat]
KeyError: 'profiles'

help/variables error: Failed: help/variables 

Error

**Comment by BjarniRunar** [comment]
Should be fixed, thanks for filing!
