### ISSUE TITLE
Random bug in IMAP handling

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1311]
Just noticed this in CLI

```
bg/log(50): Traceback (most recent call last):
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/mail_source/__init__.py", line 787, in run
    self.sync_mail()
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/mail_source/__init__.py", line 188, in sync_mail
    if batch > 0 and (self._has_mailbox_changed(mbx_cfg, state) or
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/mail_source/imap.py", line 699, in _has_mailbox_changed
    uv = state['uv'] = src.mailbox_info('UIDVALIDITY', ['0'])[0]
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/mail_source/imap.py", line 350, in mailbox_info
    imap.select(self.path)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/mail_source/imap.py", line 201, in select
    ('FLAGS', 'EXISTS', 'RECENT', 'UIDVALIDITY'))
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/mail_source/imap.py", line 200, in <genexpr>
    info = dict(self._conn.response(f) for f in
AttributeError: 'NoneType' object has no attribute 'response'
```

**Comment by BjarniRunar** [comment]
Thanks for filing this. I think I've tracked it down to a locking oversight, will push fix up soon.
