### ISSUE TITLE
Weird hang / crash occured

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1317]
Reminiscent of bugs from threads / locks bugs. I hadn't been doing anything, in fact my laptop and Mailpile had just been idling on the desk and upon refreshing in the browser, the first part of this stack trace printed in browser. 

```
bg/log(10): search error: Failed: search in:inbox
bg/log(50): Traceback (most recent call last):
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/httpd.py", line 410, in _real_do_GET
    results = [cmd.run() for cmd in commands]
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/commands.py", line 628, in run
    return self._run(*args, **kwargs)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/commands.py", line 620, in _run
    return self._run_sync(True, *args, **kwargs)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/commands.py", line 592, in _run_sync
    return self._finishing(False)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/commands.py", line 532, in _finishing
    self._update_finished_event()
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/commands.py", line 543, in _update_finished_event
    self._update_event_state(Event.COMPLETE, log=True)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/commands.py", line 468, in _update_event_state
    self.session.config.event_log.log_event(self.event)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/eventlog.py", line 355, in log_event
    self._save_events([event])
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/eventlog.py", line 252, in _save_events
    self._log_fd.write('%s\n' % event)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/crypto/streamer.py", line 209, in write
    return self._fd.write(self._write_filter(data), *args, **kwargs)
AttributeError: 'NoneType' object has no attribute 'write'

bg/log(20): http://localhost:33411 "GET /in/inbox/ HTTP/1.1" 500 1524

mailpile> quit
Popen(['openssl', 'enc', '-e', '-a', '-aes-256-cbc', '-pass', 'stdin', '-bufsize', '0'], <open file '<fdopen>', mode 'w+b' at 0x119321270>, False)
Traceback (most recent call last):
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/crypto/streamer.py", line 161, in __init__
    self._proc, self._fd = self._popen(command, fd, long_running)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/crypto/streamer.py", line 202, in _popen
    bufsize=0, long_running=long_running)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/safe_popen.py", line 153, in __init__
    creationflags=creationflags)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1223, in _execute_child
    errpipe_read, errpipe_write = self.pipe_cloexec()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1175, in pipe_cloexec
    r, w = os.pipe()
OSError: [Errno 24] Too many open files

Traceback (most recent call last):
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/commands.py", line 583, in _run_sync
    return self._finishing(command(self, *args, **kwargs))
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/commands.py", line 581, in command
    return self.command(*args, **kwargs)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/commands.py", line 2331, in command
    self._background_save(index=True, config=True, wait=True)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/commands.py", line 361, in _background_save
    cfg.flush_mbox_cache(session, clear=False, wait=wait)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/config.py", line 1776, in flush_mbox_cache
    unique=True)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/workers.py", line 212, in do
    rv = task()
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/config.py", line 1775, in <lambda>
    drop=clear, force_save=True),
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/config.py", line 1740, in uncache_mailbox
    self.save_mailbox(session, pfn, mboxes[0])
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/config.py", line 1724, in save_mailbox
    to=pfn, pickler=lambda o, f: self.save_pickle(o, f))
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/mailboxes/__init__.py", line 119, in save
    pickler(self, fn)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/config.py", line 1724, in <lambda>
    to=pfn, pickler=lambda o, f: self.save_pickle(o, f))
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/config.py", line 1700, in save_pickle
    name='save_pickle') as fd:
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/crypto/streamer.py", line 494, in EncryptingStreamer
    return EncryptingUndelimitedStreamer(*args, **kwargs)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/crypto/streamer.py", line 402, in __init__
    use_filter=use_filter)
  File "/Users/brennannovak/MailpileCode/Mailpile/
quit error: Failed: quit 
Traceback (most recent call last):
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/commands.py", line 583, in _run_sync
    return self._finishing(command(self, *args, **kwargs))
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/commands.py", line 581, in command
    return self.command(*args, **kwargs)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/app.py", line 125, in command
    Interact(session)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/app.py", line 84, in Interact
    result = Action(session, opt, arg)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/commands.py", line 2634, in Action
    return command(session, opt, arg, data=data).run()
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/commands.py", line 632, in run
    return self._run(*args, **kwargs)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/commands.py", line 620, in _run
    return self._run_sync(True, *args, **kwargs)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/commands.py", line 592, in _run_sync
    return self._finishing(False)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/commands.py", line 532, in _finishing
    self._update_finished_event()
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/commands.py", line 543, in _update_finished_event
    self._update_event_state(Event.COMPLETE, log=True)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/commands.py", line 468, in _update_event_state
    self.session.config.event_log.log_event(self.event)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/eventlog.py", line 355, in log_event
    self._save_events([event])
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/eventlog.py", line 252, in _save_events
    self._log_fd.write('%s\n' % event)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/crypto/streamer.py", line 209, in write
    return self._fd.write(self._write_filter(data), *args, **kwargs)
AttributeError: 'NoneType' object has no attrib
interact error: Failed: interact 
Popen(['openssl', 'enc', '-e', '-a', '-aes-256-cbc', '-pass', 'stdin', '-bufsize', '0'], <open file '<fdopen>', mode 'w+b' at 0x10a261db0>, False)
Traceback (most recent call last):
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/crypto/streamer.py", line 161, in __init__
    self._proc, self._fd = self._popen(command, fd, long_running)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/crypto/streamer.py", line 202, in _popen
    bufsize=0, long_running=long_running)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/safe_popen.py", line 153, in __init__
    creationflags=creationflags)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1223, in _execute_child
    errpipe_read, errpipe_write = self.pipe_cloexec()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1175, in pipe_cloexec
    r, w = os.pipe()
OSError: [Errno 24] Too many open files

bg/log(50): Traceback (most recent call last):
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/workers.py", line 260, in run
    session.report_task_completed(name, task())
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/commands.py", line 359, in <lambda>
    aut(session, 'Save config', lambda: cfg.save(session))
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/config.py", line 1509, in save
    self._unlocked_save(*args, **kwargs)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/config.py", line 1592, in _unlocked_save
    name='Config') as fd:
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/crypto/streamer.py", line 494, in EncryptingStreamer
    return EncryptingUndelimitedStreamer(*args, **kwargs)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/crypto/streamer.py", line 402, in __init__
    use_filter=use_filter)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/crypto/streamer.py", line 264, in __init__
    long_running=long_running)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/crypto/streamer.py", line 161, in __init__
    self._proc, self._fd = self._popen(command, fd, long_running)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/crypto/streamer.py", line 202, in _popen
    bufsize=0, long_running=long_running)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/safe_popen.py", line 153, in __init__
    creationflags=creationflags)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1223, in _execute_child
    errpipe_read, errpipe_write = self.pipe_cloexec()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1175, in pipe_cloexec
    r, w = os.pipe()
OSError: [Errno 24] Too many open files

bg/log(10): Save config failed in Save worker: [Errno 24] Too many open files
Exception in thread Maildirs:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/mail_source/__init__.py", line 813, in run
    self._log_status(_('Shut down'))
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/mail_source/__init__.py", line 100, in _log_status
    self.session.config.event_log.log_event(self.event)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/eventlog.py", line 355, in log_event
    self._save_events([event])
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/eventlog.py", line 252, in _save_events
    self._log_fd.write('%s\n' % event)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/crypto/streamer.py", line 209, in write
    return self._fd.write(self._write_filter(data), *args, **kwargs)
AttributeError: 'NoneType' object has no attribute 'write'

Waiting for <Worker(Async worker, started 4552302592)>: Finished refresh_command_cache (2s, jobs=1, jobs_after=0)
Waiting for <Worker(Slow worker, started 4543889408)>: Rescan (3133s, jobs=2, jobs_after=0)
Starting: Save config
```

**Comment by BjarniRunar** [comment]
Hmm, too many open files.

I am going to close this as a "won't fix", because this code is slated for wholesale replacement when the new storage code is ready for merging. Thanks for reporting though!
