### ISSUE TITLE
Error on looking up PGP key from keyserver

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1323]
Not sure what this is about, caused a slight flicker in lookup dialogue to flash, and then jumped to displaying "key is already in my keychain"

```
mailpile> Traceback (most recent call last):
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/plugins/keylookup/__init__.py", line 143, in lookup_crypto_keys
    get=(wanted if (get is not None) else None))
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/util.py", line 891, in work
    result.append(func(*args, **kwargs))
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/plugins/keylookup/__init__.py", line 290, in lookup
    all_keys = self._lookup(address, strict_email_match=strict_email_match)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/plugins/keylookup/dnspka.py", line 50, in _lookup
    return self._keyinfo(entry)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/plugins/keylookup/dnspka.py", line 69, in _keyinfo
    raise ValueError("We only know how to deal with pka version 1")
ValueError: We only know how to deal with pka version 1
```

**Comment by BjarniRunar** [comment]
You must have debugging switched on, which means you sometimes get some internal debug spam on your console. This is all perfectly normal, AFAICT. :-)

**Comment by bnvk** [comment]
Yes, I do in fact have debugging switched on. If there is no way that such a thing would bubble up the UI, then leave this closed, otherwise there is something else that made the modal flicker and not provide accurate information in the first place.
