### ISSUE TITLE
KeyError on importing mail

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1324]
```
Traceback (most recent call last):
  File "/root/Mailpile/mailpile/commands.py", line 583, in _run_sync
    return self._finishing(command(self, *args, **kwargs))
  File "/root/Mailpile/mailpile/commands.py", line 581, in command
    return self.command(*args, **kwargs)
  File "/root/Mailpile/mailpile/commands.py", line 1178, in command
    which=which))
  File "/root/Mailpile/mailpile/commands.py", line 1341, in _rescan_mailboxes
    event=self.event)
  File "/root/Mailpile/mailpile/search.py", line 743, in scan_mailbox
    msg_ptr = mbox.get_msg_ptr(mailbox_idx, i)
  File "/root/Mailpile/mailpile/mailboxes/mbox.py", line 160, in get_msg_ptr
    msg_start = self._toc[toc_id][0]
KeyError: 1

rescan error: Failed: rescan mailboxes
Elapsed: 0.077s (rescan: Failed: rescan mailboxes)
```

**Comment by BjarniRunar** [comment]
I think this is an edge case caused by background rescanning interfering with the manual rescan you've triggered. Having looked at the code, a race condition like that is really the only way this could happen. This is  not something most users will ever encounter and when it happens the app will recover and rescan that mailbox again later.

I think failing gracefully is the right behaviour for an edge case like this. It's certainly "good enough" at this point in time. Thanks for reporting it though!
