### ISSUE TITLE
Opensssl memory errors

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1327]
While performing basic tag creating and tagging ops on my "monster pile" things started not responding, the CLI showed this memory error:

```
Popen(['openssl', 'enc', '-e', '-a', '-aes-256-cbc', '-pass', 'stdin', '-bufsize', '0'], <open file '<fdopen>', mode 'w+b' at 0x7f796bda89c0>, False)
Traceback (most recent call last):
  File "/root/Mailpile/mailpile/crypto/streamer.py", line 161, in __init__
    self._proc, self._fd = self._popen(command, fd, long_running)
  File "/root/Mailpile/mailpile/crypto/streamer.py", line 202, in _popen
    bufsize=0, long_running=long_running)
  File "/root/Mailpile/mailpile/safe_popen.py", line 153, in __init__
    creationflags=creationflags)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1231, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

also, seem unable to perform `quit` command via the CLI now due the memory error repeating!

**Comment by BjarniRunar** [comment]
This is not a Mailpile issue - your box has run out of RAM!

Mailpile could be less of a memory-hog, which might help reduce the frequency of this, but that's a different issue (and one that is already on our roadmap and tracked elsewhere).
