### ISSUE TITLE
Reply in message thread fails

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1330]
After pulling in changes for the Beta III, replying to messages in threads errors out with no feedback in the UI. Upon investigating in the JS, the API call to `api/0/message/update/send/`returns the following:

```
{
 "command": "mail", 
 "elapsed": "0.013", 
 "event_id": "55ab9160.01075.b43e", 
 "message": "Failed: mail ", 
 "result": false, 
 "state": {
  "cache_id": "", 
  "command_url": "/message/update/send/", 
  "context": "", 
  "context_url": "/message/update/send/", 
  "query_args": {
   "end": [], 
   "order": [
    "rev-date"
   ], 
   "q": [], 
   "qr": [], 
   "start": []
  }
 }, 
 "status": "error"
}
```

**And here is the print out of the stack trace form CLI which offer more information**

```
bg/log(20): Elapsed: 0.000s (output: Set output mode to: json)
bg/log(50): Traceback (most recent call last):
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/commands.py", line 583, in _run_sync
    return self._finishing(command(self, *args, **kwargs))
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/commands.py", line 581, in command
    return self.command(*args, **kwargs)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/plugins/compose.py", line 1009, in command
    return Update.command(self, create=create, outbox=outbox)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/plugins/compose.py", line 974, in command
    email.update_from_string(session, update_string, final=outbox)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/mailutils.py", line 706, in update_from_string
    sender, rcpts, outmsg, ev = PrepareMessage(self.config, outmsg)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/mailutils.py", line 295, in PrepareMessage
    config, sender, rcpts, msg)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/plugins/__init__.py", line 544, in outgoing_email_content_transform
    return self._txf_out(self.OUTGOING_EMAIL_CONTENT, cfg, s, r, m, kwa)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/plugins/__init__.py", line 530, in _txf_out
    s, r, msg, match, cont = txf.TransformOutgoing(s, r, msg, **kwa)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/plugins/crypto_gnupg.py", line 44, in TransformOutgoing
    for p in crypto_format.split('+')
AttributeError: 'NoneType' object has no attribute 'split'

bg/log(10): mail error: Failed: mail
```

**Comment by BjarniRunar** [comment]
Thank you!

**Comment by bnvk** [comment]
I can confirm it's fixed. Thanks!
