### ISSUE TITLE
broken links crash mailpile browse feature

### ISSUE THREAD

**Issue by pravi** [mailpile/Mailpile#1359]
OSError: [Errno 2] No such file or directory: '/home/pravi/ruby-vegas_0.1.11.orig.tar.gz'
Traceback (most recent call last):
  File "/home/pravi/forge/mailpile/Mailpile/mailpile/commands.py", line 1759, in command
    file_list.extend(ls(path))
  File "/home/pravi/forge/mailpile/Mailpile/mailpile/commands.py", line 1752, in ls
    if '-a' in flags or f.raw_fp[:1] != '.']
  File "/home/pravi/forge/mailpile/Mailpile/mailpile/commands.py", line 1745, in lsf
    info = vfs.getinfo(f, self.session.config)
  File "/home/pravi/forge/mailpile/Mailpile/mailpile/vfs.py", line 161, in getinfo
    return cls.getinfo_(FilePath(fp).raw_fp, config)
  File "/home/pravi/forge/mailpile/Mailpile/mailpile/vfs.py", line 169, in getinfo_
    'bytes': cls.getsize(fp),
  File "/home/pravi/forge/mailpile/Mailpile/mailpile/vfs.py", line 211, in getsize
    return cls.getsize_(FilePath(fp).raw_fp)
  File "/home/pravi/forge/mailpile/Mailpile/mailpile/vfs.py", line 266, in getsize_
    return self._delegate(path).getsize_(path, *args, **kwargs)
  File "/home/pravi/forge/mailpile/Mailpile/mailpile/vfs.py", line 296, in getsize_
    def getsize_(self, path): return os.path.getsize(path)
  File "/usr/lib/python2.7/genericpath.py", line 49, in getsize
    return os.stat(filename).st_size
OSError: [Errno 2] No such file or directory: '/home/pravi/ruby-vegas_0.1.11.orig.tar.gz'

After commenting on #897 I tried again and figured its a broken link that caused a crash. Broken links should be ignored.

**Comment by BjarniRunar** [comment]
Thanks for filing this! Should be an easy fix.
