### ISSUE TITLE
Calling "search" command from CLI when unauthenticated throws error

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1368]
When not authenticated to my Mailpile and calling `contacts` and perhaps other commands from the CLI a nice message is displayed which says `contacts error: Please log in`

However, when running the `search` command a more nasty looking error is shown. Ideally this should show a similar message prompting user to login!

```
mailpile> contacts
contacts error: Please log in
Elapsed: 0.000s (contacts: Please log in)

Failed: Please log in

mailpile> search
Traceback (most recent call last):
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/commands.py", line 558, in _run_sync
    self._starting()
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/plugins/search.py", line 86, in _starting
    session, idx = self.session, self._idx()
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/commands.py", line 318, in _idx
    session, config = self.session, self._config()
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/commands.py", line 310, in _config
    config.load(session)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/config.py", line 1369, in load
    return self._unlocked_load(*args, **kwargs)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/config.py", line 1425, in _unlocked_load
    public=True)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/config.py", line 1467, in _unlocked_load
    raise IOError('Failed to load main config')
IOError: Failed to load main config

search error: Failed: search 
Traceback (most recent call last):
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/commands.py", line 282, in cache_result
    self.cache_requirements(result),
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/plugins/search.py", line 185, in cache_requirements
    msgs = self.session.results[self._start:self._start + self._num]
AttributeError: 'Search' object has no attribute '_start'
```

**Comment by BjarniRunar** [comment]
This is expected. The errors could be prettier (making the CLI prettier is worth doing, but not high priority), but you can't search when you're not logged in.
