### ISSUE TITLE
Running export errors out

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#1392]
```
mailpile> order rev-flat-date

mailpile> search in:lists

mailpile> export --flat all mbox:/Users/bumblesnort/Messages/lists.mbx
Traceback (most recent call last):
  File "/Users/bumblesnort/MailpileCode/Mailpile/mailpile/commands.py", line 585, in _run_sync
    return self._finishing(command(self, *args, **kwargs))
  File "/Users/bumblesnort/MailpileCode/Mailpile/mailpile/commands.py", line 583, in command
    return self.command(*args, **kwargs)
  File "/Users/bumblesnort/MailpileCode/Mailpile/mailpile/plugins/exporters.py", line 120, in command
    header, body = data.split(lf+lf, 1)
ValueError: need more than 1 value to unpack

export error: Failed: export --flat all mbox:/Users/bumblesnort/Messages/lists.mbx
Elapsed: 142.262s (export: Failed: export --flat all mbox:/Users/bumblesnort/Messages/lists.mbx)

Failed: Failed: export --flat all mbox:/Users/bumblesnort/Messages/lists.mbx
```

**Comment by bnvk** [comment]
This is intermittent, the majority of exports seem to complete ok, but a couple fail with the above message!
