### ISSUE TITLE
GPG key generation failed 

### ISSUE THREAD

**Issue by FSMaxB** [mailpile/Mailpile#1489]
I was adding a new email account and generating a 4096 bit key. This triggered a notification saying "GPG key generation failed" or something like that  and I got this message on the mailpile console:

```
Mailpile> Boo! GET_LINE keygen.algo not found in [GNUPG:] GET_LINE keygen.name

Traceback (most recent call last):
  File "/mnt/data/synced/Dokumente/Basteleien/Mailpile/mailpile/crypto/gpgi.py", line 1199, in run
    self.run_script, self.main_script)
  File "/mnt/data/synced/Dokumente/Basteleien/Mailpile/mailpile/crypto/gpgi.py", line 987, in chat
    return callback(proc, *args, **kwargs)
  File "/mnt/data/synced/Dokumente/Basteleien/Mailpile/mailpile/crypto/gpgi.py", line 1186, in run_script
    self.expect_exact(proc, exp, timeout=tmo)
  File "/mnt/data/synced/Dokumente/Basteleien/Mailpile/mailpile/crypto/gpgi.py", line 1175, in expect_exact
    if RunTimed(timeout, self._expecter, proc, exp, timebox):
  File "/mnt/data/synced/Dokumente/Basteleien/Mailpile/mailpile/util.py", line 942, in RunTimed
    RunTimedThread(func.__name__, work).run_timed(timeout)
  File "/mnt/data/synced/Dokumente/Basteleien/Mailpile/mailpile/util.py", line 931, in run_timed
    raise TimedOut('Timed out: %s' % self.name)
TimedOut: Timed out: _expecter
```

I was using the configuration auto detection.

GnuPG version:
```
$ LANG=en_US.UTF-8 gpg --version
gpg (GnuPG) 2.1.10
libgcrypt 1.6.4
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: ~/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

**Comment by FSMaxB** [comment]
This might probably be related to #1216. I'm using commit 6406e1e41deb712881f608f2c930fd3cbaab658f

**Comment by BjarniRunar** [comment]
Thank you for filing, the details you provide are exactly what I need to diagnose this!

And the verdict is: Mailpile is not compatible with GnuPG 2.x.

Follow #1133 for updates. ;-)
