### ISSUE TITLE
Can't send mails with attachments

### ISSUE THREAD

**Issue by dymat** [mailpile/Mailpile#1562]
Hi there,

I am unable to send mails with files attached. When I hit the Send button simply nothing happens if there are any attachments (without attachments it works just fine).

Maybe this could be a hint:
Since the mail was stored in Drafts folder I tried to edit and send it from terminal. But when I saved the changes to send out the mail this error traceback was printed:

```
Traceback (most recent call last):
  File "/home/dymat/Mailpile/mailpile/commands.py", line 592, in _run_sync
    return self._finishing(command(self, *args, **kwargs))
  File "/home/dymat/Mailpile/mailpile/commands.py", line 590, in command
    return self.command(*args, **kwargs)
  File "/home/dymat/Mailpile/mailpile/plugins/search.py", line 383, in command
    rv = self._side_effects(emails)
  File "/home/dymat/Mailpile/mailpile/plugins/compose.py", line 305, in _side_effects
    elif session.ui.edit_messages(session, emails):
  File "/home/dymat/Mailpile/mailpile/ui.py", line 575, in edit_messages
    emails[i].update_from_string(session, updates[i])
  File "/home/dymat/Mailpile/mailpile/mailutils.py", line 828, in update_from_string
    for att in oldtree['attachments']:
KeyError: 'attachments'
```

Best regards and thanks for your great work!
dymat

**Comment by BjarniRunar** [comment]
Thank you for filing this. I'll try and get it fixed soon. :-)

**Comment by JocelynDelalande** [comment]
I can confirm it fails

**Comment by JocelynDelalande** [comment]
This failure is recent, I didn't accurately bisected but just random-tested a quite-recent commit and the bug is not present at 28b3c975d32a2719a1e329bd868c70236dc0d93e

**Comment by BjarniRunar** [comment]
Yes, I know how I broke this. This will get fixed within a couple of days, sorry about the inconvenience.

**Comment by BjarniRunar** [comment]
Pretty sure this has been fixed. Thanks for filing! :-)
