### ISSUE TITLE
Unable to log in after [Errno 28] No space left on device

### ISSUE THREAD

**Issue by fmfrisch** [mailpile/Mailpile#1575]
Had it up and running just fine, but ran out of space and because of that I am unable to log in. It says password is wrong. Given that mailpile encrypts its content this seems like a pretty serious bug. Full log:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/Mailpile/mailpile/mail_source/__init__.py", line 916, in run
    self._log_status(_('Internal error!  Sleeping...'))
  File "/Mailpile/mailpile/mail_source/__init__.py", line 167, in _log_status
    self.session.config.event_log.log_event(self.event)
  File "/Mailpile/mailpile/eventlog.py", line 366, in log_event
    self._save_events([event])
  File "/Mailpile/mailpile/eventlog.py", line 259, in _save_events
    self._open_log()
  File "/Mailpile/mailpile/eventlog.py", line 231, in _open_log
    long_running=True)
  File "/Mailpile/mailpile/crypto/streamer.py", line 494, in EncryptingStreamer
    return EncryptingUndelimitedStreamer(*args, **kwargs)
  File "/Mailpile/mailpile/crypto/streamer.py", line 402, in __init__
    use_filter=use_filter)
  File "/Mailpile/mailpile/crypto/streamer.py", line 261, in __init__
    self._write_preamble()
  File "/Mailpile/mailpile/crypto/streamer.py", line 465, in _write_preamble
    self.fd.flush()
IOError: [Errno 28] No space left on device

y", line 592, in _run_sync                                                     
    return self._finishing(command(self, *args, **kwargs))
  File "/Mailpile/mailpile/commands.py", line 590, in command
    return self.command(*args, **kwargs)
  File "/Mailpile/mailpile/commands.py", line 1621, in command
    self._background_save(config=True)
  File "/Mailpile/mailpile/commands.py", line 365, in _background_save
    aut(session, 'Save config', lambda: cfg.save(session), first=True)
  File "/Mailpile/mailpile/workers.py", line 367, in add_unique_task
    return self.add_task(session, name, task)
  File "/Mailpile/mailpile/workers.py", line 364, in add_task
    return task()
  File "/Mailpile/mailpile/commands.py", line 365, in <lambda>
    aut(session, 'Save config', lambda: cfg.save(session), first=True)
  File "/Mailpile/mailpile/config.py", line 1585, in save
    self._unlocked_save(*args, **kwargs)
  File "/Mailpile/mailpile/config.py", line 1652, in _unlocked_save
    fd.write(self.as_config_bytes(_type='public'))
IOError: [Errno 28] No space left on device
```

**Comment by fmfrisch** [comment]
Once space is freed up, the log in works again

**Comment by BjarniRunar** [comment]
Thanks for reporting this!

We definitely need to explore what breaks when Mailpile runs out of resources, this is important.

**Comment by BjarniRunar** [comment]
This reported behaviour is actually very good; since Mailpile can't usefully do anything if it's out of disk space, refusing to start is the right thing to do. The fact that you could then log in again later means Things Are Working.

However, I rather suspect that Mailpile will still crap its pants and do bad things if it runs out of disk space after you have logged in. I'll file a new issue for that.

**Comment by BjarniRunar** [comment]
Filed #1696 to improve overall behaviour.
