### ISSUE TITLE
Can't see mails in INBOX over IMAP

### ISSUE THREAD

**Issue by hythloday** [mailpile/Mailpile#1578]
New installation of mailpile, small inbox that's been running a couple of weeks, running against Dovecot. Thunderbird sees all mails fine. Same error trying to look at mails in Trash.

```
mailpile> eventlog/watch
Watching logs: Press CTRL-C to return to the CLI
http/log(20): Elapsed: 0.001s (output: Set output mode to: as.jhtml!content)
56d06bab-0002a-7057=ListDir:c ls: Listed 2 files or directories
http/log(20): Elapsed: 0.003s (ls: Listed 2 files or directories)
bg/log(20): http://localhost:33411 "GET /browse/as.jhtml!content HTTP/1.1" 200 4747
http/log(20): Elapsed: 0.063s (Sending response)
http/log(20): Elapsed: 7.283s (eventlog: Found 1 events)
bg/log(20): http://localhost:33411 "GET /api/0/logs/events/?since=1456499620.44949&gather=1&wait=30 HTTP/1.1" 200 1023
http/log(20): Elapsed: 7.286s (Sending response)
http/log(20): Elapsed: 0.001s (output: Set output mode to: json)
http/log(20): Elapsed: 0.001s (output: Set output mode to: as.jhtml!content)
56d06343-00083-6d41=ImapMailSource:R Connected to IMAP server fitch.weaselnest.org.uk
bg/log(50): <ImapMailSource(therese@fitch.weaselnest.org.uk, started 140076457649920)>: Idle(279): Connected to IMAP server fitch.weaselnest.org.uk
bg/log(50): CONNECTED <SharedImapConn(fitch.weaselnest.org.uk, started daemon 140075996280576)>
bg/log(50): CAPABILITIES set(['SASL-IR', 'ENABLE', 'IDLE', 'AUTH=LOGIN', 'IMAP4REV1', 'LOGIN-REFERRALS', 'AUTH=PLAIN', 'LITERAL+', 'ID'])
bg/log(50): NAMESPACES {'private': []}
bg/log(50): list(('', '%') {})
bg/log(50):  => ('OK', ['(\\HasNoChildren \\Trash) "." Trash', '(\\HasNoChildren) "." INBOX'])
56d06bad-0002e-7057=ListDir:c ls: Listed 2 files or directories
http/log(20): Elapsed: 0.088s (ls: Listed 2 files or directories)
bg/log(20): http://localhost:33411 "GET /browse/src:a4d56d062e1/as.jhtml!content HTTP/1.1" 200 5229
http/log(20): Elapsed: 0.095s (Sending response)
http/log(20): Elapsed: 2.120s (eventlog: Found 2 events)
bg/log(20): http://localhost:33411 "GET /api/0/logs/events/?since=1456499627.743374&gather=1&wait=30 HTTP/1.1" 200 2752
http/log(20): Elapsed: 2.124s (Sending response)
http/log(20): Elapsed: 0.001s (output: Set output mode to: json)
http/log(20): Elapsed: 0.000s (output: Set output mode to: as.jhtml!content)
bg/log(50): select(INBOX, True) = ('OK', ['21']) {'UIDVALIDITY': ['1456497491'], 'FLAGS': ['(\\Answered \\Flagged \\Deleted \\Seen \\Draft Junk NonJunk)'], 'EXISTS': ['21'], 'RECENT': ['0']}
bg/log(50): uid(('SEARCH', None, 'ALL') {})
bg/log(50):  => ('OK', ['1 2 3 4 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22'])
bg/log(50): uid(('SEARCH', None, 'ALL') {})
bg/log(50):  => ('OK', ['1 2 3 4 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22'])
http/log(50): Traceback (most recent call last):
  File "/home/mailpile/Mailpile/mailpile/commands.py", line 592, in _run_sync
    return self._finishing(command(self, *args, **kwargs))
  File "/home/mailpile/Mailpile/mailpile/commands.py", line 590, in command
    return self.command(*args, **kwargs)
  File "/home/mailpile/Mailpile/mailpile/plugins/search.py", line 269, in command
    session, idx = self._do_search()
  File "/home/mailpile/Mailpile/mailpile/plugins/search.py", line 207, in _do_search
    idx.sort_results(session, session.results, session.order)
  File "/home/mailpile/Mailpile/mailpile/search.py", line 2135, in sort_results
    all_new |= self.TAGS[tag._key]
KeyError: 'd'

http/log(10): search error: Failed: search
http/log(50): Traceback (most recent call last):
  File "/home/mailpile/Mailpile/mailpile/commands.py", line 286, in cache_result
    self.cache_requirements(result),
  File "/home/mailpile/Mailpile/mailpile/plugins/search.py", line 259, in cache_requirements
    [fix_term(t) for t in self.session.searched] +
  File "/home/mailpile/Mailpile/mailpile/plugins/search.py", line 255, in fix_term
    raise ValueError('VFS searches are not cached')
ValueError: VFS searches are not cached

56d06baf-00032-7057=Search:c search: Failed: search
```

I had a look at the code around search.py#2135 but it wasn't clear to me what it's looking at - catching the exception and continuing crashed in a different place. Any advice or further debugging I can do?

**Comment by BjarniRunar** [comment]
Thank you for reporting this. I have had other reports of the KeyError reported above, I will try to look into this soon.

**Comment by eldios** [comment]
As commented in 
https://github.com/cbrouwer/Mailpile/commit/b1708c98df6ed60a2a0c513a9ab1683e4530156a
that lil' patch fixed it for me. Thanks to @cbrouwer !
