### ISSUE TITLE
GPG creation fails

### ISSUE THREAD

**Issue by dkm** [mailpile/Mailpile#1600]
Same as https://github.com/mailpile/Mailpile/issues/1489
But with gpg 1.4.1, on debian stable with mailpile up-to-date wrt master of this morning : 74d1eea99bdb892555b0cf191b612b9340df1c48

```
mailpile> Boo! GET_LINE keygen.email not found in 
[GNUPG:] GOT_IT
[GNUPG:] GET_LINE keygen.name

Traceback (most recent call last):
  File "/srv/www-lu/www/mailpile/virt-env/local/lib/python2.7/site-packages/mailpile/crypto/gpgi.py", line 1512, in run
    gpg.chat(self.gpg_args(), self.run_script, self.main_script)
  File "/srv/www-lu/www/mailpile/virt-env/local/lib/python2.7/site-packages/mailpile/crypto/gpgi.py", line 1301, in chat
    return callback(proc, *args, **kwargs)
  File "/srv/www-lu/www/mailpile/virt-env/local/lib/python2.7/site-packages/mailpile/crypto/gpgi.py", line 1498, in run_script
    self.expect_exact(proc, exp, timeout=tmo)
  File "/srv/www-lu/www/mailpile/virt-env/local/lib/python2.7/site-packages/mailpile/crypto/gpgi.py", line 1487, in expect_exact
    if RunTimed(timeout, self._expecter, proc, exp, timebox):
  File "/srv/www-lu/www/mailpile/virt-env/local/lib/python2.7/site-packages/mailpile/util.py", line 948, in RunTimed
    RunTimedThread(func.__name__, work).run_timed(timeout)
  File "/srv/www-lu/www/mailpile/virt-env/local/lib/python2.7/site-packages/mailpile/util.py", line 937, in run_timed
    raise TimedOut('Timed out: %s' % self.name)
TimedOut: Timed out: _expecter

```
```

$ gpg --version
gpg (GnuPG) 1.4.18
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: ~/.gnupg
Supported algorithms:
Pubkey: RSA, RSA-E, RSA-S, ELG-E, DSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: MD5, SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2

```

**Comment by rikmendes** [comment]
I'm using Archlinux and it seems I have 2 version of gnupg installed : 
1.4.18 and 2.1.14 so I'm wondering how I can "tell" to Mailpile which of the gnupg to use ?

**Comment by BjarniRunar** [comment]
@dkm: Thanks for filing. I am pretty sure this is a dup of #1480, where key creation can time-out or fail because of insufficient entropy. Closing as such.

@rikmendes: Mailpile uses by default whatever is "gpg" on the command-line.  If you need to change this, you can do this at the mailpile> prompt: `set sys.gpg_binary = /path/to/gpg1.4`
