### ISSUE TITLE
GPG Key generation fails (2048 bits)

### ISSUE THREAD

**Issue by Epse** [mailpile/Mailpile#1652]
I got this error message in console, with just a notification about the failure in the ui.
`Traceback (most recent call last):
  File "/home/epse/Documents/Programming/MailpileFork/mailpile/crypto/gpgi.py", line 1512, in run
    gpg.chat(self.gpg_args(), self.run_script, self.main_script)
  File "/home/epse/Documents/Programming/MailpileFork/mailpile/crypto/gpgi.py", line 1301, in chat
    return callback(proc, *args, **kwargs)
  File "/home/epse/Documents/Programming/MailpileFork/mailpile/crypto/gpgi.py", line 1498, in run_script
    self.expect_exact(proc, exp, timeout=tmo)
  File "/home/epse/Documents/Programming/MailpileFork/mailpile/crypto/gpgi.py", line 1487, in expect_exact
    if RunTimed(timeout, self._expecter, proc, exp, timebox):
  File "/home/epse/Documents/Programming/MailpileFork/mailpile/util.py", line 948, in RunTimed
    RunTimedThread(func.__name__, work).run_timed(timeout)
  File "/home/epse/Documents/Programming/MailpileFork/mailpile/util.py", line 937, in run_timed
    raise TimedOut('Timed out: %s' % self.name)
TimedOut: Timed out: _expecter`

Don't know what caused the error. Running latest from the git, not a release version.

**Comment by Epse** [comment]
Found to be duplicate for #1480 
Closing this one
