### ISSUE TITLE
PGP key generation failed!

### ISSUE THREAD

**Issue by loidor** [mailpile/Mailpile#1720]
Every time I try to create a pgp key through web ui, I get a notification saying **PGP key generation failed!** I can't see why that is. It works however just fine if I run the same gpg line in the mailpile cli, but only after running rngd that creates some extra entropy.

The event log:
```
{
 "data": {
  "gnupg": [
   [
    "Creating a 2048 bit GnuPG key", 
    1481126019, 
    "gpg --utf8-strings --no-use-agent --no-tty --command-fd=0 --status-fd=1 --no-use-agent --gen-key", 
    "GnuPG returned -1"
   ]
  ], 
  "keygen_failed": true, 
  "keygen_finished": 1481126024, 
  "keygen_started": 1481126019, 
  "profile_id": "e82584737b2"
 }, 
 "date": "Wed, 07 Dec 2016 15:53:44 -0000", 
 "event_id": "58483083-0003e-2996", 
 "flags": "c", 
 "message": "PGP key generation failed!", 
 "private_data": {
  "bits": 2048, 
  "comment": "", 
  "email": "*********@gmail.com", 
  "gnupg": [
   [
    "Creating a 2048 bit GnuPG key", 
    1481126019, 
    "gpg --utf8-strings --no-use-agent --no-tty --command-fd=0 --status-fd=1 --no-use-agent --gen-key", 
    "GnuPG returned -1"
   ]
  ], 
  "name": "Erik \u00d6hrn", 
  "passphrase": "......."
 }, 
 "source": ".plugins.contacts.EditProfile", 
 "ts": 1481126024.810252
}
```

**Comment by BjarniRunar** [comment]
Dunno if that was your real passphrase in the log snippet, but I've edit it away "just in case". Thank you for posting this.

If you type gpg --version, what does it say?

Also, if you run rngd to generate entropy first, does the Mailpile generation succeed?

**Comment by aviau** [comment]
> Dunno if that was your real passphrase in the log snippet, but I've edit it away "just in case".

@loidor 

By the way, some people like me are subscribed to GitHub email notifications. I still have a copy of the original submission. So act accordingly.

**Comment by loidor** [comment]
No, that's not the real passphrase, but a pseudo.

It doesn't seem to care if i run rngd or not - the web ui doesn't want to create a PGP key anyway. 

Also, I'm aware it's not to be run as root per se - I've set up a ubuntu 16.10 server so mailpile is running as a service through screen. However, the same issue is repeated even when I don't run it through screen and if I run it as user rather than root.

gpg --version gives:
```
root@lithium:~# gpg --version
gpg (GnuPG) 2.1.15
libgcrypt 1.7.2-beta
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /root/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

Mailpile CLI gives:
```
Boo! GET_LINE keygen.algo not found in [GNUPG:] GET_LINE keygen.name

Traceback (most recent call last):
  File "/opt/mailpile/mailpile/crypto/gpgi.py", line 1512, in run
    gpg.chat(self.gpg_args(), self.run_script, self.main_script)
  File "/opt/mailpile/mailpile/crypto/gpgi.py", line 1301, in chat
    return callback(proc, *args, **kwargs)
  File "/opt/mailpile/mailpile/crypto/gpgi.py", line 1498, in run_script
    self.expect_exact(proc, exp, timeout=tmo)
  File "/opt/mailpile/mailpile/crypto/gpgi.py", line 1487, in expect_exact
    if RunTimed(timeout, self._expecter, proc, exp, timebox):
  File "/opt/mailpile/mailpile/util.py", line 977, in RunTimed
    RunTimedThread(func.__name__, work).run_timed(timeout)
  File "/opt/mailpile/mailpile/util.py", line 966, in run_timed
    raise TimedOut('Timed out: %s' % self.name)
TimedOut: Timed out: _expecter
```

**Comment by BjarniRunar** [comment]
Right. Mailpile only works with gnupg 1.4. :-)

See #1133, closing as a dup...
