### ISSUE TITLE
Internal error (IMAP)

### ISSUE THREAD

**Issue by kode54** [mailpile/Mailpile#1739]
After so much runtime, I start to see in my log:

```
Exception in thread kode54@gmail.com:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Mailpile/mailpile/mail_source/__init__.py", line 875, in run
    self._log_status(_('Internal error!  Sleeping...'))
  File "/Mailpile/mailpile/mail_source/__init__.py", line 167, in _log_status
    self.session.config.event_log.log_event(self.event)
  File "/Mailpile/mailpile/eventlog.py", line 355, in log_event
    self._save_events([event])
  File "/Mailpile/mailpile/eventlog.py", line 252, in _save_events
    self._log_fd.write('%s\n' % event)
  File "/Mailpile/mailpile/crypto/streamer.py", line 209, in write
    return self._fd.write(self._write_filter(data), *args, **kwargs)
AttributeError: 'NoneType' object has no attribute 'write'
```

**Comment by BjarniRunar** [comment]
Thank you for reporting this, that shouldn't be happening!
