### ISSUE TITLE
python error after login

### ISSUE THREAD

**Issue by maysara** [mailpile/Mailpile#1762]
Greetings again,

So I just updated mp today (and my ubuntu 16.04 as well) and I changed my mail password; just in case this might be relevant... once I enter my mp pw, I get the following error, and the web ui says "invalid username or password":

mailpile> Traceback (most recent call last):
  File "/home/uwe/code/Mailpile/mailpile/crypto/streamer.py", line 197, in run
    self._copy_loop()
  File "/home/uwe/code/Mailpile/mailpile/crypto/streamer.py", line 184, in _copy_loop
    self.writing_to.write(self.callback(None) or '')
  File "/home/uwe/code/Mailpile/mailpile/crypto/streamer.py", line 812, in _read_data
    return process(None)
  File "/home/uwe/code/Mailpile/mailpile/crypto/streamer.py", line 801, in process
    data += self.decryptor(self.decoder(d))
  File "/usr/lib/python2.7/base64.py", line 78, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding
Traceback (most recent call last):
  File "/home/uwe/code/Mailpile/mailpile/crypto/streamer.py", line 197, in run
    self._copy_loop()
  File "/home/uwe/code/Mailpile/mailpile/crypto/streamer.py", line 184, in _copy_loop
    self.writing_to.write(self.callback(None) or '')
  File "/home/uwe/code/Mailpile/mailpile/crypto/streamer.py", line 812, in _read_data
    return process(None)
  File "/home/uwe/code/Mailpile/mailpile/crypto/streamer.py", line 801, in process
    data += self.decryptor(self.decoder(d))
  File "/usr/lib/python2.7/base64.py", line 78, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding
Traceback (most recent call last):
  File "/home/uwe/code/Mailpile/mailpile/crypto/streamer.py", line 197, in run
    self._copy_loop()
  File "/home/uwe/code/Mailpile/mailpile/crypto/streamer.py", line 184, in _copy_loop
    self.writing_to.write(self.callback(None) or '')
  File "/home/uwe/code/Mailpile/mailpile/crypto/streamer.py", line 812, in _read_data
    return process(None)
  File "/home/uwe/code/Mailpile/mailpile/crypto/streamer.py", line 801, in process
    data += self.decryptor(self.decoder(d))
  File "/usr/lib/python2.7/base64.py", line 78, in b64decode
    raise TypeError(msg)
TypeError: Incorrect padding

**Comment by JocelynDelalande** [comment]
Getting same after upgrading my "production" instance to latest master. The process then continues, I still can access my old emails, but it seems that new ones ain't fetched.

**Comment by BjarniRunar** [comment]
@JocelynDelalande I've just merged a fix which should prevent these issues from crashing threads. However, the underlying problem is data corruption, so this isn't necessarily a complete solution, depending on what caused the corruption in the first place.

Stack traces may still appear, but they should have more helpful information - in particular, which file contains the bad data.

**Comment by JocelynDelalande** [comment]
@BjarniRunar Thanks !

Here is the more explicit error that I get now :
```
Traceback (most recent call last):
  File "/home/jocelyn/Mailpile/mailpile/crypto/streamer.py", line 197, in run
    self._copy_loop()
  File "/home/jocelyn/Mailpile/mailpile/crypto/streamer.py", line 184, in _copy_loop
    self.writing_to.write(self.callback(None) or '')
  File "/home/jocelyn/Mailpile/mailpile/crypto/streamer.py", line 820, in _read_data
    return process(None)
  File "/home/jocelyn/Mailpile/mailpile/crypto/streamer.py", line 810, in process
    % self.name)
IOError: EventLog/DS(588e7d33-0253e-269): Bad data, failed to decode
```

And the mailpile web ui after that error at startup still says « Updating search engine for INBOX  » forever (in notifications), and never gets new emails.

Any ideas ?

**Comment by JocelynDelalande** [comment]
@maysara did this error actually prevent something from working ? (after upgrading to recent master)

**Comment by maysara** [comment]
Well, It seems to work now, I still get the following in the logs:

console.error: addendum: 
  Warning: flattenChildren(...): Encountered two children with the same key, `.0:$Some string that I cannot find in my mailbox nor mailpile code`. Child keys must be unique; when two children share a key, only the first child will be used.

[... this shows up again...]

Traceback (most recent call last):
  File "/path_to_Mailpile/mailpile/crypto/streamer.py", line 197, in run
    self._copy_loop()
  File "/path_to_Mailpile/mailpile/crypto/streamer.py", line 184, in _copy_loop
    self.writing_to.write(self.callback(None) or '')
  File "/path_to_Mailpile/mailpile/crypto/streamer.py", line 820, in _read_data
    return process(None)
  File "/path_to_Mailpile/mailpile/crypto/streamer.py", line 810, in process
    % self.name)
IOError: EventLog/DS(587fe40f-0c62f-10e6): Bad data, failed to decode

Thanks !

**Comment by BjarniRunar** [comment]
Hi @maysara - that flattenChildren message is probably coming from your web browser, which may have been launched on Mailpile startup.

The stacktrace you mention is (mostly) harmless, but is indicative of the fact that Mailpile probably didn't shut down cleanly before.

I'm going to close this, please feel free to open a new issue if you have more problems! And thank you for filing the issue in the first place.
