### ISSUE TITLE
Give user better feedback when PGP key creation times out

### ISSUE THREAD

**Issue by Kabouik** [mailpile/Mailpile#1848]
Hi,

Pretty much what the title says: when I add an account to a new installation of Mailpile (up to date, I git cloned today), set security to GPG 2048 encryption, and then save, the account will synchronize emails and start downloading them, but the notification about GPG 2048 key being created stays and will never succeed. After several tens of minutes, the terminal says: 

```
Boo! KEY_CREATED not found in 
[GNUPG:] ERROR key_generate 67141713
[GNUPG:] KEY_NOT_CREATED 

Traceback (most recent call last):
  File "/media/stockage/Data/Emails/Mailpile/mailpile/crypto/gpgi.py", line 1587, in run
    gpg.chat(self.gpg_args(), self.run_script, self.main_script)
  File "/media/stockage/Data/Emails/Mailpile/mailpile/crypto/gpgi.py", line 1369, in chat
    return callback(proc, *args, **kwargs)
  File "/media/stockage/Data/Emails/Mailpile/mailpile/crypto/gpgi.py", line 1573, in run_script
    self.expect_exact(proc, exp, timeout=tmo)
  File "/media/stockage/Data/Emails/Mailpile/mailpile/crypto/gpgi.py", line 1561, in expect_exact
    if RunTimed(timeout, self._expecter, proc, exp, timebox):
  File "/media/stockage/Data/Emails/Mailpile/mailpile/util.py", line 1010, in RunTimed
    RunTimedThread(func.__name__, work).run_timed(timeout)
  File "/media/stockage/Data/Emails/Mailpile/mailpile/util.py", line 999, in run_timed
    raise TimedOut('Timed out: %s' % self.name)
TimedOut: Timed out: _expecter
Boo! KEY_CREATED not found in 
[GNUPG:] ERROR key_generate 67141713
[GNUPG:] KEY_NOT_CREATED 

Traceback (most recent call last):
  File "/media/stockage/Data/Emails/Mailpile/mailpile/crypto/gpgi.py", line 1587, in run
    gpg.chat(self.gpg_args(), self.run_script, self.main_script)
  File "/media/stockage/Data/Emails/Mailpile/mailpile/crypto/gpgi.py", line 1369, in chat
    return callback(proc, *args, **kwargs)
  File "/media/stockage/Data/Emails/Mailpile/mailpile/crypto/gpgi.py", line 1573, in run_script
    self.expect_exact(proc, exp, timeout=tmo)
  File "/media/stockage/Data/Emails/Mailpile/mailpile/crypto/gpgi.py", line 1561, in expect_exact
    if RunTimed(timeout, self._expecter, proc, exp, timebox):
  File "/media/stockage/Data/Emails/Mailpile/mailpile/util.py", line 1010, in RunTimed
    RunTimedThread(func.__name__, work).run_timed(timeout)
  File "/media/stockage/Data/Emails/Mailpile/mailpile/util.py", line 999, in run_timed
    raise TimedOut('Timed out: %s' % self.name)
TimedOut: Timed out: _expecter
```

I'm running Solus x64, latest version of Mailpile with fresh installation (no pre-existing configuration or accounts), gpg version 2.1.21.

Am I doing something wrong?

**Comment by Kabouik** [comment]
Okay, turns out rebooting my computer and trying again made it work instantly. After reading [this](https://unix.stackexchange.com/questions/318385/no-such-file-or-directory-when-generating-a-gpg-key), I am guessing something was wrong with ~/.gnupg and not with Mailpile itself. Sorry for the inconvenience.

**Comment by BjarniRunar** [comment]
When a machine is low on entropy, key generation may take too long / time out. This is IMO a GnuPG issue for demanding an unreasonable amount of entropy for key generation, but we should still handle it more gracefully and provide the user with helpful feedback to explain what is going on.

I'm going to rename this issue and leave it open to track that aspect of the problem. Relates to #912.

**Comment by BjarniRunar** [comment]
Woops, this is a duplicate of #1480
