### ISSUE TITLE
Mailpile fails to open on second load

### ISSUE THREAD

**Issue by danyill** [mailpile/Mailpile#1919]
After leaving Mailpile running almost a week, moving about 20K emails or so I shut it down and restarted my computer.

When I try to restart it, I get the following error generated after I enter my user password and the webpage fails to load:

```
$ mailpile
Failed to load language C                                                      
Failed to configure i18n (C). Using fallback.                                  
Elapsed: 0.003s (health: We are healthy!)                                      
Elapsed: 0.001s (motd: Message Of The Day: Loaded)
=============================================================================
Mailpile.py              a tool             Copyright 2013-2017, Mailpile ehf
 v1.0.0rc1         for searching and               <https://www.mailpile.is/>
               organizing piles of e-mail

This program is free software: you can redistribute it and/or modify it under
the terms of either the GNU Affero General Public License as published by the
Free Software Foundation. See the file COPYING.md for details.

The Web interface address is: http://localhost:33411/

   * Type `help` for instructions or `quit` to quit.
   * Long running operations can be aborted by pressing: <CTRL-C>
   * You can log in using the `login` command.
   * Check your web browser!

Message Of The Day, 2017-08-11:

    Hello world!
    
    Our first 1.0 release candidate is available from www.mailpile.is. Debian packages and joy! Check it out.

*** Your Mailpile is up to date ***

mailpile> Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mailpile/crypto/streamer.py", line 195, in run
    self._copy_loop()
  File "/usr/lib/python2.7/dist-packages/mailpile/crypto/streamer.py", line 182, in _copy_loop
    self.writing_to.write(self.callback(None) or '')
  File "/usr/lib/python2.7/dist-packages/mailpile/crypto/streamer.py", line 819, in _read_data
    return process(None)
  File "/usr/lib/python2.7/dist-packages/mailpile/crypto/streamer.py", line 809, in process
    % self.name)
IOError: EventLog/DS(599f6e8c-b0fe0-3c4c): Bad data, failed to decode
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mailpile/crypto/streamer.py", line 195, in run
    self._copy_loop()
  File "/usr/lib/python2.7/dist-packages/mailpile/crypto/streamer.py", line 182, in _copy_loop
    self.writing_to.write(self.callback(None) or '')
  File "/usr/lib/python2.7/dist-packages/mailpile/crypto/streamer.py", line 819, in _read_data
    return process(None)
  File "/usr/lib/python2.7/dist-packages/mailpile/crypto/streamer.py", line 809, in process
    % self.name)
IOError: EventLog/DS(599f7f71-0002e-6eb2): Bad data, failed to decode

```

When I go back to `http://localhost:33411` in my browser, I find it is working fine and responds to searches etc.

I don't know what this means, happy to provide further information if some instructions to so can be given to the technologically doubtful :smile:

**Comment by BjarniRunar** [comment]
Thanks for reporting - that's a known issue. It's "mostly harmless," I will get it cleaned up one of these days...
