### ISSUE TITLE
[query] How can I start Mailpile as a background web service?

### ISSUE THREAD

**Issue by kwill** [mailpile/Mailpile#1940]
I assumed that `mailpile www` was the method to start Mailpile without the command line interface and without automatically launching my browser. Is this correct?

```
$ mailpile www
Failed to load language C                                                      
Failed to configure i18n (C). Using fallback.                                  
Elapsed: 0.002s (health: We are healthy!)                                      
Elapsed: 0.002s (www: Started the web server on http://localhost:33411/)       
OK: Started the web server on http://localhost:33411/
Traceback (most recent call last):
  File "/usr/bin/mailpile", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/mailpile/__main__.py", line 6, in main
    Main(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/mailpile/app.py", line 247, in Main
    readline.write_history_file(session.config.history_file())
AttributeError: 'NoneType' object has no attribute 'write_history_file'
```

(Traceback reported in #1941)

**Comment by kwill** [comment]
**Workaround:** Create an xdg-desktop file that starts Mailpile in a terminal. The first launch will open a terminal window and launch a browser tab. Subsequent launches will fail (a new terminal windows will open then fail and close). If you accidently close the terminal window, just launch the xdg-desktop icon again.

**Example:** (~/.share/applications/mailpile.desktop)

```
[Desktop Entry]
Version=1.0
Type=Application
Exec=mailpile
StartupNotify=true
Terminal=true
Keywords=Email
Name=Mailpile
Comment=A free & open modern, fast email client with user-friendly encryption and privacy features
```

**Comment by kwill** [comment]
Looking at https://github.com/mailpile/Mailpile/blob/master/shared-data/multipile/mailpile-admin.py it seems that you can't strictly do this yet. Instead, mailpile-admin creates a screen session.

See the MAILPILE_START_SCRIPT definition in the link above.

**Comment by kwill** [comment]
Also, it looks like `mailpile-apache2` is currently the best supported way to do this right now.
