### ISSUE TITLE
All invocations end with a traceback: AttributeError on write_history_file

### ISSUE THREAD

**Issue by kwill** [mailpile/Mailpile#1941]
All invocations except just `mailpile` end with a traceback. For example `mailpile help`:

```
$ mailpile help
Failed to load language C                                                      
Failed to configure i18n (C). Using fallback.                                  
Elapsed: 0.005s (health: We are healthy!)                                      
Failed to load language C                                                      
Failed to configure i18n (C). Using fallback.                                  
Commands:played help                                                           
    load                    Load or reload the metadata index
    idlequit [<timeout>]    Shut down Mailpile if it has been idle for a while
    interact   
  q|quit     [restart]      Exit Mailpile, normal shutdown
    wait       
    health                  Check and report app health
    browse_o                Launch browser and exit, if already running
    cat      </path/to/file> [>/path/to/output]
                            Dump the contents of a file, decrypting if necessary
    cd       <.../new/path/...>
                            Change working directory
    cleanup                 Perform cleanup actions (runs before shutdown)
    login                   Authenticate a user (log in)
    logout   [<session ID>] De-authenticate a user (log out)
    ls       [-a] [-d] [</path/*.foo> ...]
                            Display working directory listing
    pidfile  </path/to/pidfile>
                            Write the PID to a file
    pipe     [e@mail.com|command|>filename] -- [<cmd> [args ... ]]
                            Pipe a command to a shell command, file or e-mail
    ps                      Display list of running threads, locks and outstanding events.
    www      [<host:port/path>]
                            Just run the web server
    motd     [--silent|--ifnew] [--[no]update|--check]
                            Download and/or display the Message Of The Day
    output   [json|text|html|<template>.html|...]
                            Choose format for command results.

  S|set      [--force] <section.variable> <value>
                            Change a setting
  P|print    [-short|-secrets|-flat] <var>
                            Print one or more settings
  h|help     [<command-group>]
                            Print help on Mailpile or individual commands.
Traceback (most recent call last):
  File "/usr/bin/mailpile", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/mailpile/__main__.py", line 6, in main
    Main(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/mailpile/app.py", line 247, in Main
    readline.write_history_file(session.config.history_file())
AttributeError: 'NoneType' object has no attribute 'write_history_file'
```

**Comment by BjarniRunar** [comment]
Looks like you don't have the Python readline module, and our code is broken in that case. Will fix the code, you can avoid the problem in the meantime by installing readline. :)
