### ISSUE TITLE
Overhaul internal CLI help output

### ISSUE THREAD

**Issue by lofidevops** [mailpile/Mailpile#1942]
`mailpile help` lists the following command:

```
browse_o                Launch browser and exit, if already running
```

but calling `mailpile browse_o` results in an `Unknown command: browse_o` error.

```
$ mailpile browse_o
Failed to load language C                                                      
Failed to configure i18n (C). Using fallback.                                  
Elapsed: 0.002s (health: We are healthy!)                                      
Unknown command: browse_o                                                      
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mailpile/app.py", line 235, in Main
    session.fatal_error(unicode(e))
  File "/usr/lib/python2.7/dist-packages/mailpile/ui.py", line 808, in fatal_error
    sys.exit(1)
SystemExit: 1
Traceback (most recent call last):
  File "/usr/bin/mailpile", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/mailpile/__main__.py", line 6, in main
    Main(sys.argv[1:])
  File "/usr/lib/python2.7/dist-packages/mailpile/app.py", line 247, in Main
    readline.write_history_file(session.config.history_file())
AttributeError: 'NoneType' object has no attribute 'write_history_file'
```

(Secondary traceback reported in #1941)

**Comment by BjarniRunar** [comment]
Looks like the help template truncates the command. Thanks for reporting this.

**Comment by BjarniRunar** [comment]
Hijacking this issue... the above is just one of many examples where the CLI `help` command now gives unhelpful output. We need to iterate on this a bit at some point, the old approach is probably not really workable as there are now too many commands for a single flat list.
