### ISSUE TITLE
Mailpile on WSL (ubuntu on Windows)

### ISSUE THREAD

**Issue by maysara** [mailpile/Mailpile#1968]
Trying to run mailpile on WSL on windows, after overcoming a few hiccups (getting packages up-to-date, mostly pip); things seem to work fine until i reach adding the accont, mailpile never gets back, looking into debug/logs does not reavel any errors or warnings; it just keeps fetching GET /api/... ; getting HTTP response 200, then every now and then I get: 
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 52422)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 593, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/XXX/code/Mailpile/mailpile/httpd.py", line 561, in finish_request
    SimpleXMLRPCServer.finish_request(self, request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 651, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 703, in finish
    if not self.wfile.closed:
  File "/home/XXX/code/Mailpile/mailpile/util.py", line 1026, in __getattribute__
    self.dbg.write('==(%d.%s)\n' % (self.fd.fileno(), name))
  File "/home/XXX/code/Mailpile/mailpile/util.py", line 1027, in __getattribute__
    return object.__getattribute__(self.fd, name)
AttributeError: 'DebugFileWrapper' object has no attribute 'fileno'

This goes on endlessly, If i quit mailpile from the command line and start it again, i'm back to first step of setting a password ... again, no errors (except for some exception that has to do with renice I guess):

Exception in thread Scan worker:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/uwe/code/Mailpile/mailpile/workers.py", line 264, in run
    play_nice(self.NICE_PRIORITY)  # Reduce priority
  File "/home/uwe/code/Mailpile/mailpile/util.py", line 835, in play_nice
    os.nice(niceness)
OSError: [Errno 1] Operation not permitted

can avoid it if i switch to root (within WSL); still the infinite loop described above still persists....

**Comment by maysara** [comment]
I removed the files in ~/.local and started a fresh setup ... this time it worked like a charm :/
