### ISSUE TITLE
Document that % needs escaping as %% in translations

### ISSUE THREAD

**Issue by BotQ** [mailpile/Mailpile#1974]
When I was debugging polish translation I realized, that sometimes (for example on home screen) exception is thrown: 

```
mailpile> Traceback (most recent call last):
  File "/home/botq/Desktop/Mailpile-master/mailpile/ui.py", line 406, in display_result
    template=template)
  File "/home/botq/Desktop/Mailpile-master/mailpile/commands.py", line 208, in as_template
    [tpath], data)
  File "/home/botq/Desktop/Mailpile-master/mailpile/ui.py", line 506, in render_web
    return template.render(alldata)
  File "/home/botq/Desktop/Mailpile-master/mp-virtualenv/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/botq/Desktop/Mailpile-master/mp-virtualenv/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/botq/Desktop/Mailpile-master/shared-data/default-theme/html/jsapi/index.js", line 445, in top-level template code
    {% include("jsapi/global/silly.js") %}
  File "/home/botq/Desktop/Mailpile-master/shared-data/default-theme/html/jsapi/global/silly.js", line 93, in top-level template code
    '{{_("Did you know humans share 50 percent of their DNA with a banana? Freaky")|escapejs}}',
  File "/home/botq/Desktop/Mailpile-master/mp-virtualenv/local/lib/python2.7/site-packages/jinja2/ext.py", line 134, in _gettext_alias
    return __context.call(__context.resolve('gettext'), *args, **kwargs)
  File "/home/botq/Desktop/Mailpile-master/mp-virtualenv/local/lib/python2.7/site-packages/jinja2/ext.py", line 143, in gettext
    return rv % variables
  File "/usr/lib/python2.7/dist-packages/markupsafe/__init__.py", line 101, in __mod__
    return self.__class__(text_type.__mod__(self, arg))
ValueError: unsupported format character 'D' (0x44) at index 33
```

When I change translation to not use % char, everything works. So % is forbidden in translation? If yes, a little information in Wiki/Translation would be nice.

**Comment by BjarniRunar** [comment]
The % symbol is not forbidden, but it needs to be escaped - To get a % to appear in the user-visible translated string, you need to write %%.

Documenting this somewhere would indeed make sense!
