### ISSUE TITLE
Broken pipey crash

### ISSUE THREAD

**Issue by melroy89** [mailpile/Mailpile#2029]
Hi,

Using the latest Mailpile version: v1.0.0rc2.   

**Expected behavior:** Profile settings should be saved successfully.

**Actual behavior:** The client crashes and was unresponsive, and I needed to restart manually to make it work again.

I went to my profile settings. I checked some setting and uncheck it again. Finally I pressed the save button. I got:
```
mailpile> <StreamWriter(gpgi-output(gpg --status-fd=2 --passphrase-fd=0 --pinentry-mode=loopback --personal-digest-preferences=SHA512     --digest-algo=SHA512 --cert-digest-algo=SHA512 --enable-progress-filter --batch --verbose --with-colons --utf8-strings --decrypt), started   140355823458048)>(gpgi-output(gpg --status-fd=2 --passphrase-fd=0 --pinentry-mode=loopback --personal-digest-preferences=SHA512  --digest-algo=SHA512 --cert-digest-algo=SHA512 --enable-progress-filter --batch --verbose --with-colons --utf8-strings --decrypt)/write): 829896 bytes left                                                                                                                                       
  Traceback (most recent call last):                                                                                                               
  File "/usr/lib/python2.7/dist-packages/mailpile/crypto/gpgi.py", line 462, in writeout
      fd.write(line)    
IOError: [Errno 32] Broken pipey
```

Kind regards,
Melroy

**Comment by BjarniRunar** [comment]
What version of GnuPG?  I'm actually surprised it's using GnuPG at all, did you modify any of the encryption settings from the defaults?

**Comment by danger89** [comment]
I'm running Debian Stretch.
```
which gpg                                                                                                                                                             
/usr/bin/gpg                                                                                                                                                                                  
```
Version:
```
gpg --version                                                                                                                                                         
gpg (GnuPG) 2.1.18                                                                                                                                                                            
libgcrypt 1.7.6-beta                                                                                                                                                                          
Copyright (C) 2017 Free Software Foundation, Inc.                                                                                                                                             
```
Package is installed (as expected):
```
apt -qq list gnupg                                                                                                                                                    
gnupg/stable,now 2.1.18-8~deb9u1 amd64 [installed]
```

I didn't modify the encryption settings as far I know. The problem is I forgot what I really did from the profile settings. This are one of the problems which is not easily 100% reproducible ><. I try my best to make it break it :laughing: . But in the end it looks like some kind of I/O error /time-out issue you can maybe try/except?

You are surprised it's using GNuPG? Why? Is GnuPG not the way to go, since I had this installed... Should I use some other package?

**Comment by danger89** [comment]
OK, so I did found some similar reports on closed issues.

https://github.com/mailpile/Mailpile/issues/1186#issuecomment-76496092
https://github.com/mailpile/Mailpile/issues/1186#issuecomment-76496092

And a random gist:
https://gist.github.com/Altreus/0f1b278832adf827fd8c647fa05522c3

**Comment by BjarniRunar** [comment]
Is it trying and failing to create a key?

**Comment by danger89** [comment]
Initially it created a key just fine (during the initial setup). So I have a valid PGP key already.

This error happened during editing profile settings.
No idea what Mailpile does when I press the 'save' button, but it looks like decrypting failed.

Ow I see you already have [a try/except statement.](https://github.com/mailpile/Mailpile/blob/master/mailpile/crypto/gpgi.py#L462). uhm. I don't know why Mailpile was not responsive anymore after this error.

**Comment by danger89** [comment]
I see it more often happening in console log.

```
ailpile> <StreamWriter(gpgi-output(gpg --status-fd=2 --passphrase-fd=0 --pinentry-mode=loopback --personal-digest-preferences=SHA512 --digest-algo=SHA512 --cert-digest-algo=SHA512 --enable-progress-filter --batch --verbose --with-colons --utf8-strings --decrypt), started 140367632262912)>(gpgi-output(gpg --status-fd=2 --passphrase-fd=0 --pinentry-mode=loopback --personal-digest-preferences=SHA512 --digest-algo=SHA512 --cert-digest-algo=SHA512 --enable-progress-filter --batch --verbose --with-colons --utf8-strings --decrypt)/write): 489981 bytes left
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mailpile/crypto/gpgi.py", line 462, in writeout
    fd.write(line)
IOError: [Errno 32] Broken pipe
<StreamWriter(gpgi-output(gpg --status-fd=2 --passphrase-fd=0 --pinentry-mode=loopback --personal-digest-preferences=SHA512 --digest-algo=SHA512 --cert-digest-algo=SHA512 --enable-progress-filter --batch --verbose --with-colons --utf8-strings --decrypt), started 140367327123200)>(gpgi-output(gpg --status-fd=2 --passphrase-fd=0 --pinentry-mode=loopback --personal-digest-preferences=SHA512 --digest-algo=SHA512 --cert-digest-algo=SHA512 --enable-progress-filter --batch --verbose --with-colons --utf8-strings --decrypt)/write): 829896 bytes left
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mailpile/crypto/gpgi.py", line 462, in writeout
    fd.write(line)
IOError: [Errno 32] Broken pipe
<StreamWriter(gpgi-output(gpg --status-fd=2 --passphrase-fd=0 --pinentry-mode=loopback --personal-digest-preferences=SHA512 --digest-algo=SHA512 --cert-digest-algo=SHA512 --enable-progress-filter --batch --verbose --with-colons --utf8-strings --decrypt), started 140367369860864)>(gpgi-output(gpg --status-fd=2 --passphrase-fd=0 --pinentry-mode=loopback --personal-digest-preferences=SHA512 --digest-algo=SHA512 --cert-digest-algo=SHA512 --enable-progress-filter --batch --verbose --with-colons --utf8-strings --decrypt)/write): 489981 bytes left
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mailpile/crypto/gpgi.py", line 462, in writeout
    fd.write(line)
IOError: [Errno 32] Broken pipe
<StreamWriter(gpgi-output(gpg --status-fd=2 --passphrase-fd=0 --pinentry-mode=loopback --personal-digest-preferences=SHA512 --digest-algo=SHA512 --cert-digest-algo=SHA512 --enable-progress-filter --batch --verbose --with-colons --utf8-strings --decrypt), started 140368090371840)>(gpgi-output(gpg --status-fd=2 --passphrase-fd=0 --pinentry-mode=loopback --personal-digest-preferences=SHA512 --digest-algo=SHA512 --cert-digest-algo=SHA512 --enable-progress-filter --batch --verbose --with-colons --utf8-strings --decrypt)/write): 489981 bytes left
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mailpile/crypto/gpgi.py", line 462, in writeout
    fd.write(line)
IOError: [Errno 32] Broken pipe
<StreamWriter(gpgi-output(gpg --status-fd=2 --passphrase-fd=0 --pinentry-mode=loopback --personal-digest-preferences=SHA512 --digest-algo=SHA512 --cert-digest-algo=SHA512 --enable-progress-filter --batch --verbose --with-colons --utf8-strings --decrypt), started 140368090371840)>(gpgi-output(gpg --status-fd=2 --passphrase-fd=0 --pinentry-mode=loopback --personal-digest-preferences=SHA512 --digest-algo=SHA512 --cert-digest-algo=SHA512 --enable-progress-filter --batch --verbose --with-colons --utf8-strings --decrypt)/write): 489981 bytes left
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/mailpile/crypto/gpgi.py", line 462, in writeout
    fd.write(line)
```

@BjarniRunar  Can I set verbose output or something? To help you guys..

**Comment by BjarniRunar** [comment]
I see this now and again myself. It's generally not a problem.

Note that Mailpile still prints quite a bit of debug junk to the terminal. Unless you actually have malfunctions in the app that coincide, things like this aren't generally cause for concern.

If you're seeing this message frequently, without the original problem:

> The client crashes and was unresponsive, and I needed to restart manually to make it work again.

Then I think we can safely assume they are unrelated.

**Comment by tpikonen** [comment]
I see similar errors on mailpile 0.99.3~1.0201806291047-1 from the Debian repo. I'm using Debian stretch as well.

These seem to correlate with a failure to get new mail from a gmail account and 'internal error' displayed on the notifications of the webapp. After restart, mailpile gets new mail again, but this happens often enough to be annoying.
