### ISSUE TITLE
Problems running Mailpile on windows

### ISSUE THREAD

**Issue by noahhaasis** [mailpile/Mailpile#2087]
I followed the developer installation guide for mailpile on windows and I get the following error message when running start .\mp.cmd: 
`Traceback (most recent call last):
  File "scripts\mailpile", line 13, in <module>
    from mailpile.app import Main
  File "C:\Projects\python\m2\Mailpile\mailpile\app.py", line 11, in <module>
    from mailpile.commands import COMMANDS, Command, Action
  File "C:\Projects\python\m2\Mailpile\mailpile\commands.py", line 14, in <module>
    from mailpile.crypto.gpgi import GnuPG
  File "C:\Projects\python\m2\Mailpile\mailpile\crypto\gpgi.py", line 37, in <module>
    GPG_BINARY = mailpile.platforms.GetDefaultGnuPGCommand()
  File "C:\Projects\python\m2\Mailpile\mailpile\platforms.py", line 20, in GetDefaultGnuPGCommand
    return _assert_file_exists('GnuPG\\gpg.exe')
  File "C:\Projects\python\m2\Mailpile\mailpile\platforms.py", line 12, in _assert_file_exists
    raise OSError('Not found: %s' % path)
OSError: Not found: GnuPG\gpg.exe

ConEmuC: Root process was alive less than 10 sec, ExitCode=0.
Press Enter or Esc to close console...`

gpg.exe is installed in C:\Program Files\GnuPG\bin.

**Comment by noahhaasis** [comment]
This can be solved by installing gpg.exe under Mailpile\GnuPG\gpg.exe. It's the same with openssl.exe which has to be installed under Mailpile\OpenSSL\bin\openssl.exe.

**Comment by BjarniRunar** [comment]
As an aside: This code is being reworked as part of our Windows packaging effort, which is ongoing.

**Comment by noahhaasis** [comment]
I want to give a quick update on my build after fixing the GnuPG and SSL issue. Maybe that's useful for the rework. If I now run `start .\mp.cmd` I get the following output:
`Elapsed: 0.491s (Loaded metadata, 0 messages)
Traceback (most recent call last):
  File "scripts\mailpile", line 14, in <module>
    Main(sys.argv[1:])
  File "C:\Projects\python\Mailpile\mailpile\app.py", line 216, in Main
    config.load(session)
  File "C:\Projects\python\Mailpile\mailpile\config\manager.py", line 321, in load
    self.gnupghome = GnuPG(self).gnupghome()
  File "C:\Projects\python\Mailpile\mailpile\crypto\gpgi.py", line 590, in gnupghome
    rv = self.run(["--version"], novercheck=True)[1]["stdout"][0]
IndexError: list index out of range`

The last index is out of range, because the second thing self.run returns is self.outputbuffers, which is set to `self.outputbuffers = dict([(x, []) for x in self.outputfds])`. self.outputfds is always `["stdout", "stderr", "status"]`. So self.outputbuffers is set to `{'status': [], 'stderr': [], 'stdout': []}`.
So the last line of the traceback could be rewritten to `{'stdout': [], 'stderr': [], 'status': []}["stdout"][0]`.
I don't see a case where this line can succeed but I would be happy if you proof me wrong.
