### ISSUE TITLE
 undefined symbol: PyFPE_jbuf

### ISSUE THREAD

**Issue by gerroon** [mailpile/Mailpile#2090]
HI

I am trying to use this on Debian Testing X64. I used https://www.mailpile.is/download/linux.html to install

When I run Mailpile this is what I get

mailpile                                                                                                                                             ⏎
Traceback (most recent call last):
  File "/usr/bin/mailpile", line 6, in <module>
    from mailpile.__main__ import main
  File "/usr/lib/python2.7/dist-packages/mailpile/__main__.py", line 2, in <module>
    from mailpile.app import Main
  File "/usr/lib/python2.7/dist-packages/mailpile/app.py", line 12, in <module>
    from mailpile.config.manager import ConfigManager
  File "/usr/lib/python2.7/dist-packages/mailpile/config/manager.py", line 35, in <module>
    from mailpile.search import MailIndex
  File "/usr/lib/python2.7/dist-packages/mailpile/search.py", line 23, in <module>
    from mailpile.mailutils.emails import ExtractEmails, ExtractEmailAndName
  File "/usr/lib/python2.7/dist-packages/mailpile/mailutils/emails.py", line 41, in <module>
    from mailpile.mailutils.html import extract_text_from_html, clean_html
  File "/usr/lib/python2.7/dist-packages/mailpile/mailutils/html.py", line 3, in <module>
    import lxml.html
  File "/usr/local/lib/python2.7/dist-packages/lxml/html/__init__.py", line 54, in <module>
    from .. import etree
ImportError: /usr/local/lib/python2.7/dist-packages/lxml/etree.so: undefined symbol: PyFPE_jbuf

**Comment by gerroon** [comment]
I do not know how I solved this, basically I installed bunch of python p[ackages and install them back, do not ask me what I did!
