### ISSUE TITLE
"mailpile-gui.py -- script" throws IOError due to a missing mailpile.sec file on macOS.

### ISSUE THREAD

**Issue by peturingi** [mailpile/Mailpile#2110]
The output of `mailpile-gui-py --script` is as follows on macOS.

```
Traceback (most recent call last):
  File "app/share/mailpile/mailpile-gui/mailpile-gui.py", line 354, in <module>
    Main(sys.argv)
  File "app/share/mailpile/mailpile-gui/mailpile-gui.py", line 332, in Main
    state = MailpileState().discover(argv)
  File "app/share/mailpile/mailpile-gui/mailpile-gui.py", line 174, in __init__
    self.secret = GetUserSecret(self.workdir)
  File "/Users/buildbot/build/Mailpile.app/Contents/Resources/app/lib/python2.7/site-packages/mailpile/security.py", line 37, in GetUserSecret
    with open(secret_file, 'w') as fd:
IOError: [Errno 2] No such file or directory: '/Users/buildbot/Library/Application Support/Mailpile/default/mailpile.sec'

```

**Comment by BjarniRunar** [comment]
This is almost certainly caused by the directory not yet existing. Will fix, thanks for reporting!
