### ISSUE TITLE
mailpile-gui / mailpile-desktop fails to launch on Debian

### ISSUE THREAD

**Issue by tpikonen** [mailpile/Mailpile#2152]
I just noticed the mailpile-desktop package on the mailpile Debian repo. Installation works, but running 'mailpile-gui.py' (it would be better to remove the .py from programs in */bin BTW) results in a splash screen and a crash:

```
$ mailpile-gui.py 
/usr/lib/python2.7/dist-packages/gui_o_matic/gui/unity.py:26: Warning: /build/glib2.0-YYXhFA/glib2.0-2.50.3/./gobject/gsignal.c:2523: signal 'child-added' is invalid for instance '0x129c128' of type 'GtkMenu'
  self.ind.set_menu(self.menu)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gui_o_matic/control/__init__.py", line 81, in do_line_magic
    self.shell_tcp_pivot(line[len(self.OK_LISTEN_TCP):].strip())
  File "/usr/lib/python2.7/dist-packages/gui_o_matic/control/__init__.py", line 64, in shell_tcp_pivot
    self._accept()
  File "/usr/lib/python2.7/dist-packages/gui_o_matic/control/__init__.py", line 48, in _accept
    self.sock = self.listening.accept()[0]
  File "/usr/lib/python2.7/socket.py", line 206, in accept
    sock, addr = self._sock.accept()
timeout: timed out
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/gui_o_matic/control/__init__.py", line 138, in run
    match, lstn = self.do_line_magic(line, None)
  File "/usr/lib/python2.7/dist-packages/gui_o_matic/control/__init__.py", line 81, in do_line_magic
    self.shell_tcp_pivot(line[len(self.OK_LISTEN_TCP):].strip())
  File "/usr/lib/python2.7/dist-packages/gui_o_matic/control/__init__.py", line 64, in shell_tcp_pivot
    self._accept()
  File "/usr/lib/python2.7/dist-packages/gui_o_matic/control/__init__.py", line 48, in _accept
    self.sock = self.listening.accept()[0]
  File "/usr/lib/python2.7/socket.py", line 206, in accept
    sock, addr = self._sock.accept()
timeout: timed out
```

The desktop client is perhaps not biggest priority in the project ATM, but, just to let you know...

**Comment by BjarniRunar** [comment]
Thank you for reporting this! I was aware that it sometimes misbehaves, but haven't gotten around to debugging the issue. It's good to have an issue to track it. :+1:
