### ISSUE TITLE
Attempt to forward a previously sent encrypted email fails

### ISSUE THREAD

**Issue by JackDca** [mailpile/Mailpile#2231]
If I receive an encrypted email, select it, open it, and then press the >Forward button at the bottom of the email, the browser screen is replaced with a screen showing unformatted text:

```
Traceback (most recent call last):
  File "/home/snorri/Work/MP/Code/MailpileDev/mailpile/httpd.py", line 496, in _real_do_GET
    mimetype, content = session.ui.render_response(session.config)
ValueError: need more than 0 values to unpack

```
This was tested with Mailpile launched from a console window. The following appears on the console:

```
Traceback (most recent call last):
  File "/home/snorri/Work/MP/Code/MailpileDev/mailpile/ui.py", line 407, in display_result
    template=template)
  File "/home/snorri/Work/MP/Code/MailpileDev/mailpile/commands.py", line 208, in as_template
    [tpath], data)
  File "/home/snorri/Work/MP/Code/MailpileDev/mailpile/ui.py", line 510, in render_web
    return template.render(alldata)
  File "/home/snorri/.local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/snorri/.local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/snorri/Work/MP/Code/MailpileDev/shared-data/default-theme/html/message/draft/index.html", line 1, in top-level template code
    {% extends "layouts/" + render_mode + "-tall.html" %}
  File "/home/snorri/Work/MP/Code/MailpileDev/shared-data/default-theme/html/layouts/full-tall.html", line 1, in top-level template code
    {%- extends "layouts/full.html" %}
  File "/home/snorri/Work/MP/Code/MailpileDev/shared-data/default-theme/html/layouts/full.html", line 1, in top-level template code
    {% extends "layouts/content.html" %}
  File "/home/snorri/Work/MP/Code/MailpileDev/shared-data/default-theme/html/layouts/content.html", line 38, in top-level template code
    {%- block content %}<h1>No Content</h1>{% endblock -%}
  File "/home/snorri/Work/MP/Code/MailpileDev/shared-data/default-theme/html/message/draft/index.html", line 38, in block "content"
    {% include("partials/error_message_missing.html") %}
  File "/home/snorri/Work/MP/Code/MailpileDev/shared-data/default-theme/html/partials/error_message_missing.html", line 3, in top-level template code
    {%- do result.__setitem__('errors', {'*': {'error': _("Message Not Found")}}) %}
TypeError: list indices must be integers, not str
```

Pressing the browser Back button goes back to the search results screen with the original received email open.

If the >Reply button is used instead of the >Forward button, there is no problem. That is, an editable compose window appears with the original email quoted in it; that email can be sent, even if the addressee is changed.

This is on Debian Stretch, commit 6e61761a dated 2019-07-20, cloned from git with a virtualenv intallation. There are two or three people with whom I have been exchanging encrypted emails now and then using email and I have never noticed this issue before, so I suspect that it has been introduced recently.

Some path names in the screen grabs above have been globally edited to confuse the malevolent.

**Comment by h3artbl33d** [comment]
I am able to replicate this on commit `#94b4b58` (28th of July), on OpenBSD-current. The last line seems most relevant, it seems to expect an integer rather than a str value. 

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/mailpile/ui.py", line 407, in display_result
    template=template)
  File "/usr/local/lib/python2.7/site-packages/mailpile/commands.py", line 208, in as_template
    [tpath], data)
  File "/usr/local/lib/python2.7/site-packages/mailpile/ui.py", line 510, in render_web
    return template.render(alldata)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/share/mailpile/default-theme/html/message/draft/index.html", line 1, in top-level template code
    {% extends "layouts/" + render_mode + "-tall.html" %}
  File "/usr/local/share/mailpile/default-theme/html/layouts/full-tall.html", line 1, in top-level template code
    {%- extends "layouts/full.html" %}
  File "/usr/local/share/mailpile/default-theme/html/layouts/full.html", line 1, in top-level template code
    {% extends "layouts/content.html" %}
  File "/usr/local/share/mailpile/default-theme/html/layouts/content.html", line 38, in top-level template code
    {%- block content %}<h1>No Content</h1>{% endblock -%}
  File "/usr/local/share/mailpile/default-theme/html/message/draft/index.html", line 38, in block "content"
    {% include("partials/error_message_missing.html") %}
  File "/usr/local/share/mailpile/default-theme/html/partials/error_message_missing.html", line 3, in top-level template code
    {%- do result.__setitem__('errors', {'*': {'error': _("Message Not Found")}}) %}
TypeError: list indices must be integers, not str
```

**Comment by JackDca** [comment]
After further testing:
This issue occurs when I attempt to "forward" an email that I originally **sent**. It does not occur when forwarding emails **received** from other people.
@h3artbl33d, does this agree with your testing?
I have edited the title to reflect this.
