### ISSUE TITLE
1.0.0rc6 fails to build on FreeBSD: ERROR:root:Error parsing

### ISSUE THREAD

**Issue by yurivict** [mailpile/Mailpile#2248]
I tried to update the FreeBSD port but it failed:
```
===>  Configuring for mailpile-1.0.0rc6
/usr/local/lib/python3.6/site-packages/pbr/core.py/usr/local/lib/python3.6/site-packages/setuptools/dist.py:46: DistDeprecationWarning: Do not call this function
  warnings.warn("Do not call this function", DistDeprecationWarning)
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/usr/local/lib/python3.6/site-packages/pbr/util.py", line 249, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/usr/local/lib/python3.6/site-packages/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/usr/local/lib/python3.6/site-packages/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/usr/local/lib/python3.6/site-packages/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/usr/local/lib/python3.6/site-packages/pbr/packaging.py", line 755, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name mailpile was given, but was not able to be found.
error in setup command: Error parsing /wrkdirs/usr/ports/mail/mailpile/work-py36/Mailpile-1.0.0rc6/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name mailpile was given, but was not able to be found.
*** Error code 1
```

**Comment by jeroenlaylo** [comment]
Mailpile isn't ready for Python 3 just yet; it should succeed on Python 2.7.

**Comment by yurivict** [comment]
Python 2.7 is EOLed.

**Comment by jeroenlaylo** [comment]
Yes. And effort is being made to migrate to v3, but there are some dependencies that that hold this back, as far as I know.

**Disclaimer:** I am not an official Mailpile dev, just an enthousiastic user (and currently tinkering a bit with it to see whether I can be of help in migrating to v3).
