### ISSUE TITLE
Handle GPG errors more gracefully and in a way that is useful to the user (renamed)

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#390]
http/log(50): Traceback (most recent call last):
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/commands.py", line 246, in _run
    return self._finishing(command, command(self, *args, **kwargs))
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/commands.py", line 243, in command
    return self.command(*args, **kwargs)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/plugins/compose.py", line 642, in command
    return Update.command(self, create=create, outbox=outbox)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/plugins/compose.py", line 597, in command
    email.update_from_string(session, update_string, final=outbox)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/mailutils.py", line 612, in update_from_string
    sender, rcpts, outmsg = PrepareMessage(self.config, outmsg)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/mailutils.py", line 206, in PrepareMessage
    recipients=rcpts).wrap(msg)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/crypto/mime.py", line 188, in wrap
    fromkey=from_key, armor=True)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/crypto/gpgi.py", line 687, in sign
    return retvals[0], retvals[1]["stdout"][0]
IndexError: list index out of range

http/log(10): Failed: message/update/send 
http/log(20): Elapsed: 0.000s (message/update/send({'body': [u'Will this get sent through to both of you cool cats?\r\n\r\nCheers, \r\nBN'], 'from': [u'Brennan Novak <hi@brennannovak.com>'], 'cc': [u''], 'encryption': [u'openpgp-sign-encrypt'], 'mid': [u'E4U'], 'bcc': [u''], 'to': [u'Bjarni Runar Einarsson <bre@pagekite.net#61A015763D28D410A87B197328191D9B3B4199B4>,Sm\xe1ri McCarthy <smari@mailpile.is#08A650B8E2CBC1B02297915DC65626EED13C70DA>'], 'subject': [u'Just A Test Encrypted Message'], '_method': 'POST'}))
http/log(5):

**Comment by BjarniRunar** [comment]
Error handling is much improved now and there are UI actions in place to handle the common cases. Things which were overlooked should get their own new issues. :-)
