### ISSUE TITLE
OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by sjjh** [mailpile/Mailpile#432]
Thanks for this great software. I added some of my Thunderbird mailboxes as explained (https://github.com/pagekite/Mailpile/wiki/Synchronizing-Mailpile-with-Thunderbird). While (re)scanning the mail boxes I get following (error) output:

``` Shell
mailpile> rescan all                                                           

Failed to load vcard pjd7_lx_zwg0_ynil9hobotrqyk.vcf                           
ERROR: syntax error while parsing MORK filell to speed up: mp --rescan=...     
context[5598]: [1E:^80][23:^80]@$${32{@{1:^80 {(k^BE:c)
ERROR: syntax error while parsing MORK file
context[5607]: 23:^80]@$${32{@{1:^80 {(k^BE:c)(s=9)} -[
ERROR: syntax error while parsing MORK file
context[5608]: 3:^80]@$${32{@{1:^80 {(k^BE:c)(s=9)} -[-
ERROR: syntax error while parsing MORK file
context[5609]: :^80]@$${32{@{1:^80 {(k^BE:c)(s=9)} -[-2
ERROR: syntax error while parsing MORK file
context[5610]: ^80]@$${32{@{1:^80 {(k^BE:c)(s=9)} -[-26
ERROR: syntax error while parsing MORK file
context[5611]: 80]@$${32{@{1:^80 {(k^BE:c)(s=9)} -[-26]
ERROR: syntax error while parsing MORK file
context[5612]: 0]@$${32{@{1:^80 {(k^BE:c)(s=9)} -[-26]}
ERROR: syntax error while parsing MORK file
context[5613]: ]@$${32{@{1:^80 {(k^BE:c)(s=9)} -[-26]}@

0000: Skipped: /home/simon/.mailpile/mail                                      
0001: Indexed mailbox: /home/simon/.thunderbird/6aohk98g.default/Mail/Local Fo 
0002: Indexed mailbox: /home/simon/.thunderbird/6aohk98g.default/Mail/Local Fo 
0003: Indexed mailbox: /home/simon/.thunderbird/6aohk98g.default/Mail/Local Fo 
0004: Indexed mailbox: /home/simon/.thunderbird/6aohk98g.default/Mail/Local Fo 
[Errno 24] Too many open files1336/1437 messages)                              
[Errno 24] Too many open files1337/1437 messages)                              
[Errno 24] Too many open files1338/1437 messages)                              
[Errno 24] Too many open files1340/1437 messages)                              
[Errno 24] Too many open files1342/1437 messages)                              
[Errno 24] Too many open files1344/1437 messages)                              
[Errno 24] Too many open files1345/1437 messages)                              
[Errno 24] Too many open files1346/1437 messages)                              
[Errno 24] Too many open files1347/1437 messages)                              
[Errno 24] Too many open files1348/1437 messages)                              
[Errno 24] Too many open files1349/1437 messages)                              
[Errno 24] Too many open files1350/1437 messages)                              
[Errno 24] Too many open files1351/1437 messages)                              
[Errno 24] Too many open files1352/1437 messages)                              
[Errno 24] Too many open files1353/1437 messages)                              
[Errno 24] Too many open files1354/1437 messages)                              
[Errno 24] Too many open files1355/1437 messages)                              
[Errno 24] Too many open files1356/1437 messages)                              
[Errno 24] Too many open files1357/1437 messages)                              
[Errno 24] Too many open files1358/1437 messages)                              
[Errno 24] Too many open files1362/1437 messages)                              
[Errno 24] Too many open files1366/1437 messages)                              
Updating search index... 0% (008rurtaj28bmd3hbrwuf1wb)                         
Traceback (most recent call last):                                             
  File "/home/simon/src/Mailpile/mailpile/commands.py", line 246, in _run
  File "/home/simon/src/Mailpile/mailpile/commands.py", line 243, in command
  File "/home/simon/src/Mailpile/mailpile/commands.py", line 681, in command
  File "/home/simon/src/Mailpile/mailpile/commands.py", line 743, in _rescan_mailboxes
  File "/home/simon/src/Mailpile/mailpile/search.py", line 237, in save_changes
  File "/home/simon/src/Mailpile/mailpile/util.py", line 354, in gpg_open
IOError: [Errno 24] Too many open files: '/home/simon/.mailpile/mailpile.idx'

Failed: rescan                                                                 

Elapsed: 346.471s (Saving metadata index changes...)                           

Failed: Add new messages to index                                              
mailpile>                                                                      
[pressed CTRL-D to abort mailiple]
Traceback (most recent call last):
  File "./mp", line 12, in <module>
  File "/home/simon/src/Mailpile/mailpile/app.py", line 167, in Main
  File "/home/simon/src/Mailpile/mailpile/search.py", line 237, in save_changes
  File "/home/simon/src/Mailpile/mailpile/util.py", line 358, in gpg_open
  File "/usr/lib/python2.7/subprocess.py", line 701, in __init__
  File "/usr/lib/python2.7/subprocess.py", line 1110, in _get_handles
  File "/usr/lib/python2.7/subprocess.py", line 1166, in pipe_cloexec
OSError: [Errno 24] Too many open files
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/apport_python_hook.py", line 64, in apport_excepthook
ImportError: No module named fileutils

Original exception was:
Traceback (most recent call last):
  File "./mp", line 12, in <module>
  File "/home/simon/src/Mailpile/mailpile/app.py", line 167, in Main
  File "/home/simon/src/Mailpile/mailpile/search.py", line 237, in save_changes
  File "/home/simon/src/Mailpile/mailpile/util.py", line 358, in gpg_open
  File "/usr/lib/python2.7/subprocess.py", line 701, in __init__
  File "/usr/lib/python2.7/subprocess.py", line 1110, in _get_handles
  File "/usr/lib/python2.7/subprocess.py", line 1166, in pipe_cloexec
OSError: [Errno 24] Too many open files
simon@laptop:~/src/Mailpile$ 
```

**Comment by JocelynDelalande** [comment]
I got the "too many open files" thing today, maybe a regression ?

**Comment by skeyl** [comment]
@JocelynDelalande can you confirm the open file limit? Do that by `cat /proc/<pid>/limits` and ousting result here.

**Comment by JocelynDelalande** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

> @JocelynDelalande can you confirm the open file limit? Do that
> by `cat /proc/<pid>/limits` and ousting result here.

Ah, sorry, I restarted mailpile since, I will think about your
advice next time, thanks :)

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.12 (GNU/Linux)

iQIcBAEBAgAGBQJWNQOqAAoJEOodh6AvlLNTztAP/i0j9TiTAcOFPAQP0k9Y8Dys
cToVWbdwjpcR0z1GmIF/ABzLLTI/9Y4kaWyrXjKaGXt1PXjPbuyyyk+zFhbJWvJJ
26Qu3GWz8br5oTg824IDZU5eLjzx7b8UNmDUxmEHc5ytNUzvsenLBPNbsvem5kFU
S4NFTtUGV7ji9LfY8mK2ekPL6uM1A9AKn8HlcWGX6p1hA4wmvQPl2UvJJ6YajJyq
vOgjv6UDhEAoz08LwYQA1Ki4aTyApS9nU8ckYOnU0Szycs1sELH899l+nGIKD+Tf
nkS3eLEwVjONziDA1eRClRGxoUC8TGz0G6gmkCrcBiKtCWckS8SH4Q3KPrGaUb9/
csYRb57cWni5Lp0V96Lz+UvW86NSSZOnN6ANHoAa2MganvMI/jaeyfr/uOeiPXBY
F45f//xxWpTgiYeBzxcCgRQo7AzM6SazuU+t6h9diaiSJvPU63rHY1ZrAyvKF4DW
ac6u3PSJRSnEt9OWtYMtmsO7aLaID8NpU0RwhkgbRH+LAzIhx369i/mFHJPA/AzU
nbsbENXC9aO59acOxEegI5xP91vQi8x2ovpo6ri1graWRiEjC3hOqkQxdHHYqDtW
C1jqolvIXQHFNHTkqK8FMSVBYRDnGHQjgfd5uI9PmDPAAX1jAz3tKFERI89lcHW8
QPQ+12nKw8ipOjb0FPv2
=ZGHY
-----END PGP SIGNATURE-----

**Comment by skeyl** [comment]
You can check now though; it'll be the same if you didn't change.

**Comment by JocelynDelalande** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

skeyl <notifications@github.com> wrote:
> You can check now though; it'll be the same if you didn't
> change.

Restarting mailpile solved the issue (closed the files ?)

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1.4.12 (GNU/Linux)

iQIcBAEBAgAGBQJWNm4FAAoJEOodh6AvlLNTRjAP/j3wzHffnGpgFwijfctMKNRV
X+oMQd5SJGe6bYpoyVr9gxJr4MsfvJy8zqLiK6/u22ajQI4rKBD9uLttz9i+eQ/m
tdDPNaNhqrBxAlkwMdv2ie4l/XNwSBN0st5CftVdgVaStkIdmWpNF4AbSawryjOD
lhSiyhMgo7Zlx/9zg/n/EDdai7madIEwgvx1BLwT2SkDD7x0rQ9HaOP7dS2tFo0P
MHH5JvutHndvkrE5d/M+L5KKKpMMu4ILzgVvtyuJ/YbtbAnqSu+45B++PP8MKE8J
TDVHc+b5uiFSVknTPKxrABtPrSzzGyrFcZK1CSY/YeKOmtEv5SOY4XHbPLFBANAl
hYlZsw7O/arVhQqtYsUjrbzSL44J8HsAokAIlsQkodD/NppL1MxqPwcUT2OVAayR
mLqsr4A/TocgOnUykPXF/6YgNFHxbHEcUM2NOoMHKoITvLe3wMScrOXReBP6Fq/s
/nidpen0NJVnRYn5Ih3aL1kIUBHGFOXwYGgQ4Ddg6rwbXuDts1BvfvEEwyh6p5GA
wUci9QU4nK6wSh32llHBtQUuzaXHQoDY2sDg5yvSvLyLo9eyWcP3xpcKUQst/J4P
tif+HkwbDoin+annGqdemQSAT/dm5qhjzHSCT8xGy0P+oBmgbxjy+6vE+P+R7XaP
UayxwNnjkDH+6PlT9fHP
=X7MP
-----END PGP SIGNATURE-----
