### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by micahflee** [mailpile/Mailpile#483]
I'm trying to get Mailpile up and working. I've followed the Linux instructions using offlineimap. But when I run ./mp and and type rescan I get this python error:

    mailpile> rescan                                                               

    Note: periodic delay is 0.02s, run from shell to speed up: mp --rescan=...     
    Traceback (most recent call last):
      File "/home/micah/projects/Mailpile/mailpile/commands.py", line 248, in _run
        return self._finishing(command, command(self, *args, **kwargs))
      File "/home/micah/projects/Mailpile/mailpile/commands.py", line 245, in command
        return self.command(*args, **kwargs)
      File "/home/micah/projects/Mailpile/mailpile/commands.py", line 682, in command
        self._rescan_vcards(session, config),
      File "/home/micah/projects/Mailpile/mailpile/commands.py", line 696, in _rescan_vcards
        imported += imp.import_vcards(session, config.vcards)
      File "/home/micah/projects/Mailpile/mailpile/vcard.py", line 829, in import_vcards
        all_vcards = self.get_vcards()
      File "/home/micah/projects/Mailpile/mailpile/plugins/vcard_gnupg.py", line 39, in get_vcards
        vcls.append(VCardLine(name="email", value=uid["email"]))
      File "/home/micah/projects/Mailpile/mailpile/vcard.py", line 59, in __init__
        self._value = unicode(value)
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

    Failed: rescan                                                                 

    Elapsed: 0.000s (rescan({}))                                                   
    Failed: Add new messages to index

**Comment by BjarniRunar** [comment]
Relates to #1228

**Comment by BjarniRunar** [comment]
I believe this was fixed in bb08e4c99e7b4d6db55b96f9e13c5b5da8bb29b0, please re-open or file a new issue if the problem persists. Thanks!
