### ISSUE TITLE
Search: UnicodeEncodeError: 'ascii' codec can't encode…

### ISSUE THREAD

**Issue by hugoroy** [mailpile/Mailpile#621]
Hi,

Just trying out Mailpile on Arch. The setup worked fine, scanned my maildir, etc.

The first search I tried (included an "é") on the web interface gave me:

     Internal error

The console output:

`````
Traceback (most recent call last):
  File "/usr/share/mailpile/mailpile/httpd.py", line 280, in do_GET
    session.ui.display_result(results[-1])
  File "/usr/share/mailpile/mailpile/ui.py", line 245, in display_result
    result.as_template(suffix, template=template))
  File "/usr/share/mailpile/mailpile/commands.py", line 146, in as_template
    data)
  File "/usr/share/mailpile/mailpile/ui.py", line 317, in render_web
    return template.render(alldata)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/share/mailpile/static/default/html/search/index.html", line 1, in top-level template code
    {% extends "layouts/" + render_mode + ".html" %}
  File "/usr/share/mailpile/static/default/html/layouts/full.html", line 179, in top-level template code
    {% include("partials/tools_search.html") %}
  File "/usr/share/mailpile/static/default/html/partials/tools_search.html", line 53, in top-level template code
    {%- include('partials/tools_default.html') -%}
  File "/usr/share/mailpile/static/default/html/partials/tools_default.html", line 36, in top-level template code
    {%- set url = elem.url|add_state_query_string(state, elem) %}
  File "/usr/share/mailpile/mailpile/jinjaextensions.py", line 131, in _add_state_query_string
    return url + '?' + urllib.urlencode(args) + frag
  File "/usr/lib/python2.7/urllib.py", line 1329, in urlencode
    v = quote_plus(str(v))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 4: ordinal not in range(128)
`````

**Comment by BjarniRunar** [comment]
This was fixed some time ago. :-)  Thanks for filing!

**Comment by hugoroy** [comment]
thanks for making mailpile :-)
