### ISSUE TITLE
Adding a mork importer as per docs fails with KeyError: u'mork'

### ISSUE THREAD

**Issue by gthb** [mailpile/Mailpile#697]
Following the [“Synchronizing Mailpile with Thunderbird” wiki page](https://github.com/pagekite/Mailpile/wiki/Synchronizing-Mailpile-with-Thunderbird), I tried this:

```
set prefs.vcard.importers.mork.0.filename = /Users/gthb/Library/Thunderbird/Profiles/deadbeef.default/abook.mab
```

and got:

```
Traceback (most recent call last):ilename = /Users/gthb/Library/Thunderbird/Pr
  File "/Users/gthb/ext/Mailpile/mailpile/commands.py", line 380, in _run
    return self._finishing(command, command(self, *args, **kwargs))
  File "/Users/gthb/ext/Mailpile/mailpile/commands.py", line 377, in command
    return self.command(*args, **kwargs)
  File "/Users/gthb/ext/Mailpile/mailpile/commands.py", line 1108, in command
    cfg, var = config.walk(path.strip(), parent=1)
  File "/Users/gthb/ext/Mailpile/mailpile/config.py", line 509, in walk
    cfg = cfg[part]
  File "/Users/gthb/ext/Mailpile/mailpile/config.py", line 527, in __getitem__
    return pcls.__getitem__(self, key)
KeyError: u'mork'

set error: Failed: set prefs.vcard.importers.mork.0.filename = /Users/gthb/Library/Thunderbird/Profiles/deadbeef.default/abook.mab

Elapsed: 0.001s (set: Failed: set prefs.vcard.importers.mork.0.filename = /Users/gthb/Library/Thunderbird/Profiles/deadbeef.default/abook.mab)
Failed: Failed: set prefs.vcard.importers.mork.0.filename = /Users/gthb/Library/Thunderbird/Profiles/deadbeef.default/abook.mab
```

(... where, unimportantly, that Traceback line apparently got printed on top of a previously printed line, and the `ilename = ...` part is in blue.)

**Comment by BjarniRunar** [comment]
Relates to #1228
