### ISSUE TITLE
Deleting filters

### ISSUE THREAD

**Issue by controesempio** [mailpile/Mailpile#754]
The delete filters command is not working at the moment:

```
mailpile> filter/list
[...]
Elapsed: 0.001s (filter/list: filter/list)
  0 user       subject:hackmeeting +hackmeeting       Filter for +hackmeeting

mailpile> filter/delete 0
[...]
Traceback (most recent call last):
  File "/Users/lucha/Code/Mailpile/mailpile/commands.py", line 430, in _run_sync
    return self._finishing(command, command(self, *args, **kwargs))
  File "/Users/lucha/Code/Mailpile/mailpile/commands.py", line 427, in command
    return self.command(*args, **kwargs)
  File "/Users/lucha/Code/Mailpile/mailpile/plugins/tags.py", line 695, in command
    if (config.parse_unset(session, 'filter:%s' % fid)
  File "/Users/lucha/Code/Mailpile/mailpile/config.py", line 565, in __getattr__
    return self[attr]
  File "/Users/lucha/Code/Mailpile/mailpile/config.py", line 544, in __getitem__
    return pcls.__getitem__(self, key)
KeyError: 'parse_unset'

filter/delete error: Failed: filter/delete 0
Elapsed: 0.001s (filter/delete: Failed: filter/delete 0)

Failed: Failed: filter/delete 0
```

I think the problem is that DeleteFilters is calling `parse_unset` (legacy code?) instead of...  maybe simply `del config.filters[fid]`? 
I haven't read the code enough to fix it myself, but I have the feeling is something trivial.

**Comment by JocelynDelalande** [comment]
This is no longer crashing on `filter/delete`. Might have been fixed via 213694291ca5cd17ec9881e79bf395312ade3ba6

Please close @BjarniRunar
