### ISSUE TITLE
setup fails: There is no assurance this key belongs to the named user

### ISSUE THREAD

**Issue by djc** [mailpile/Mailpile#756]
I removed a left-over .mailpile dir from when I tried alpha 1, and ran `mp setup`:

```
gpg: 2F0FDB12: There is no assurance this key belongs to the named user        
gpg: [stdin]: encryption failed: Unusable public key
Traceback (most recent call last):
  File "/home/djc/src/mailpile/mailpile/commands.py", line 430, in _run_sync
    return self._finishing(command, command(self, *args, **kwargs))
  File "/home/djc/src/mailpile/mailpile/commands.py", line 427, in command
    return self.command(*args, **kwargs)
  File "/home/djc/src/mailpile/mailpile/plugins/migrate.py", line 280, in command
    self._background_save(config=True)
  File "/home/djc/src/mailpile/mailpile/commands.py", line 252, in _background_save
    aut(session, 'Save config', cfg.save)
  File "/home/djc/src/mailpile/mailpile/workers.py", line 276, in add_unique_task
    return self.add_task(session, name, task)
  File "/home/djc/src/mailpile/mailpile/workers.py", line 271, in add_task
    return task()
  File "/home/djc/src/mailpile/mailpile/config.py", line 1083, in save
    self._unlocked_save(*args, **kwargs)
  File "/home/djc/src/mailpile/mailpile/config.py", line 1091, in _unlocked_save
    fd.write(self.as_config_bytes(private=True))
  File "/home/djc/src/mailpile/mailpile/util.py", line 393, in write
    self.fd.write(data)
IOError: [Errno 32] Broken pipe
```

**Comment by BjarniRunar** [comment]
This is obsolete now. Thank you all for the report and discussions.
