### ISSUE TITLE
VCard clientpidmap error showing up in stracktrace

### ISSUE THREAD

**Issue by bnvk** [mailpile/Mailpile#830]
Not sure if this an import that might be causing other issues, but i'm noticing this!

```
bg/log(50): Traceback (most recent call last):
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/commands.py", line 469, in _run_sync
    return self._finishing(command, command(self, *args, **kwargs))
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/commands.py", line 466, in command
    return self.command(*args, **kwargs)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/commands.py", line 1056, in command
    results.update(self._rescan_vcards(session))
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/commands.py", line 1081, in _rescan_vcards
    imported += imp.import_vcards(session, config.vcards)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/vcard.py", line 1266, in import_vcards
    card.merge(self.config.guid, vcard.as_lines())
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/vcard.py", line 543, in merge
    self.remove(ol.line_id)
  File "/Users/brennannovak/MailpileCode/Mailpile/mailpile/vcard.py", line 356, in remove
    % self._lines[index].name)
ValueError: Cannot remove clientpidmap from VCard

bg/log(10): rescan error: Failed: rescan 
```

**Comment by BjarniRunar** [comment]
Relates to #1228 .
