### ISSUE TITLE
Manually tagging messages as Drafts causes bad behavior

### ISSUE THREAD

**Issue by JocelynDelalande** [mailpile/Mailpile#864]
Traceback (most recent call last):
  File "/home/jocelyn/divers/Mailpile/mailpile/ui.py", line 423, in render_web
    return template.render(alldata)

  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/jocelyn/divers/Mailpile/static/default/html/message/draft.html", line 1, in top-level template code
    {% extends "layouts/" + render_mode + ".html" %}
  File "/home/jocelyn/divers/Mailpile/static/default/html/layouts/full.html", line 33, in top-level template code
    {% block content %}{{results}}{% endblock %}
  File "/home/jocelyn/divers/Mailpile/static/default/html/message/draft.html", line 26, in block "content"
    {% include("partials/compose.html") %}
  File "/home/jocelyn/divers/Mailpile/static/default/html/partials/compose.html", line 8, in top-level template code
    <a id="compose-cc-show" class="compose-show-field {% if editing_strings.cc %}hide{% endif %}" href="#">{{_("Cc")}}</a>
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 397, in getattr
    return getattr(obj, attribute)
UndefinedError: 'dict object' has no attribute 'editing_strings'

**Comment by JackDca** [comment]
I got tied up in knots after saving a draft reply to an email that was part of a conversation.

I've also experienced some strangeness when saving drafts in Thunderbird (especially if they are moved from the draft folder to another folder).  The real problem is that a draft is not the same as a received or sent email so this has to be thought out at a higher level to avoid complications.

If a message is saved as a draft, it should not take the conversation with it.  Perhaps it should be temporarily separated from the conversation, then reattached when it is next opened.

Here are the details of my problem:

There a conversation - a chain of about five emails - in the Inbox.
I opened the most recent message in the conversation and pressed "Reply".
I wrote part of the reply them pressed "Save".
This put the *** entire conversation *** effectively in the Drafts "folder".
I wanted to view one of the earlier messages in the conversation so I clicked on the Drafts icon.
This brought up the draft, but the sidebar that normally shows the entire conversation was absent, so there was no way to access the earlier emails.
After much messing around I used the handle at the left end of the item in the Drafts "folder" and dragged it to the "Inbox" which made the entire conversation accessible.
Unfortunately the draft which I had saved was now displayed as if it were a received email; specifically, there was no "Send" icon on it.  To continue editing it, I had to press the "Forward" button, of course this meant I had to fill in the "To:" address again.
Finally I sent the email.  When I did that and the BCC showed up in the Inbox, it did not appear as part of the conversation, but as a new conversation.

This put the **entire con
