### ISSUE TITLE
`vagrant up` on current master (9861ed4) reports errors, creates broken box

### ISSUE THREAD

**Issue by ginkel** [mailpile/Mailpile#910]
```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
[...]
==> default: .. initial setup (creates folders and tags)
==> default: Creating: /home/vagrant/.local/share/Mailpile/default                          
==> default: Failed to configure i18n. Using fallback.                                      
==> default: Loading plugin: crypto_utils                                                   
==> default: Loading plugin: migrate                                                        
==> default: Loading plugin: plugins                                                        
==> default: Loading plugin: vcard_carddav                                                  
==> default: Loading plugin: compose                                                        
==> default: Loading plugin: eventlog                                                       
==> default: Loading plugin: contacts                                                       
==> default: Loading plugin: keylookup                                                      
==> default: Traceback (most recent call last):
==> default:   File "./mp", line 12, in <module>
==> default:     
==> default: Main(sys.argv[1:])
==> default:   File "/srv/Mailpile/mailpile/app.py", line 144, in Main
==> default:     
==> default: config.load(session)
==> default:   File "/srv/Mailpile/mailpile/config.py", line 1233, in load
==> default:     
==> default: return self._unlocked_load(*args, **kwargs)
==> default:   File "/srv/Mailpile/mailpile/config.py", line 1292, in _unlocked_load
==> default:     
==> default: self.load_plugins(session)
==> default:   File "/srv/Mailpile/mailpile/config.py", line 1334, in load_plugins
==> default:     
==> default: self.plugins.load(plugin)
==> default:   File "/srv/Mailpile/mailpile/plugins/__init__.py", line 201, in load
==> default:     
==> default: return self._load(*args, **kwargs)
==> default:   File "/srv/Mailpile/mailpile/plugins/__init__.py", line 153, in _load
==> default:     
==> default: module = __import__(full_name)
==> default:   File "/srv/Mailpile/mailpile/plugins/keylookup/__init__.py", line 342, in <module>
==> default:     
==> default: from mailpile.plugins.keylookup.email_keylookup import EmailKeyLookupHandler
==> default:   File "/srv/Mailpile/mailpile/plugins/keylookup/email_keylookup.py", line 11, in <module>
==> default:     
==> default: import pgpdump
==> default: ImportError
==> default: : 
==> default: No module named pgpdump
==> default: .. adding a test mailbox
==> default: Failed to configure i18n. Using fallback.                                      
==> default: Loading plugin: crypto_utils                                                   
==> default: Loading plugin: migrate                                                        
==> default: Loading plugin: plugins                                                        
==> default: Loading plugin: vcard_carddav                                                  
==> default: Loading plugin: compose                                                        
==> default: Loading plugin: eventlog                                                       
==> default: Loading plugin: contacts                                                       
==> default: Loading plugin: keylookup                                                      
==> default: Traceback (most recent call last):
==> default:   File "./mp", line 12, in <module>
==> default:     
==> default: Main(sys.argv[1:])
==> default:   File "/srv/Mailpile/mailpile/app.py", line 144, in Main
==> default:     
==> default: config.load(session)
==> default:   File "/srv/Mailpile/mailpile/config.py", line 1233, in load
==> default:     
==> default: return self._unlocked_load(*args, **kwargs)
==> default:   File "/srv/Mailpile/mailpile/config.py", line 1292, in _unlocked_load
==> default:     
==> default: self.load_plugins(session)
==> default:   File "/srv/Mailpile/mailpile/config.py", line 1334, in load_plugins
==> default:     
==> default: self.plugins.load(plugin)
==> default:   File "/srv/Mailpile/mailpile/plugins/__init__.py", line 201, in load
==> default:     
==> default: return self._load(*args, **kwargs)
==> default:   File "/srv/Mailpile/mailpile/plugins/__init__.py", line 153, in _load
==> default:     
==> default: module = __import__(full_name)
==> default:   File "/srv/Mailpile/mailpile/plugins/keylookup/__init__.py", line 342, in <module>
==> default:     
==> default: from mailpile.plugins.keylookup.email_keylookup import EmailKeyLookupHandler
==> default:   File "/srv/Mailpile/mailpile/plugins/keylookup/email_keylookup.py", line 11, in <module>
==> default:     
==> default: import pgpdump
==> default: ImportError
==> default: : 
==> default: No module named pgpdump
==> default: .. rescanning everything
==> default: Failed to configure i18n. Using fallback.                                      
==> default: Loading plugin: crypto_utils                                                   
==> default: Loading plugin: migrate                                                        
==> default: Loading plugin: plugins                                                        
==> default: Loading plugin: vcard_carddav                                                  
==> default: Loading plugin: compose                                                        
==> default: Loading plugin: eventlog                                                       
==> default: Loading plugin: contacts                                                       
==> default: Loading plugin: keylookup                                                      
==> default: Traceback (most recent call last):
==> default:   File "./mp", line 12, in <module>
==> default:     
==> default: Main(sys.argv[1:])
==> default:   File "/srv/Mailpile/mailpile/app.py", line 144, in Main
==> default:     
==> default: config.load(session)
==> default:   File "/srv/Mailpile/mailpile/config.py", line 1233, in load
==> default:     
==> default: return self._unlocked_load(*args, **kwargs)
==> default:   File "/srv/Mailpile/mailpile/config.py", line 1292, in _unlocked_load
==> default:     
==> default: self.load_plugins(session)
==> default:   File "/srv/Mailpile/mailpile/config.py", line 1334, in load_plugins
==> default:     
==> default: self.plugins.load(plugin)
==> default:   File "/srv/Mailpile/mailpile/plugins/__init__.py", line 201, in load
==> default:     
==> default: return self._load(*args, **kwargs)
==> default:   File "/srv/Mailpile/mailpile/plugins/__init__.py", line 153, in _load
==> default:     
==> default: module = __import__(full_name)
==> default:   File "/srv/Mailpile/mailpile/plugins/keylookup/__init__.py", line 342, in <module>
==> default:     
==> default: from mailpile.plugins.keylookup.email_keylookup import EmailKeyLookupHandler
==> default:   File "/srv/Mailpile/mailpile/plugins/keylookup/email_keylookup.py", line 11, in <module>
==> default:     
==> default: import pgpdump
==> default: ImportError
==> default: : 
==> default: No module named pgpdump
==> default: 
==> default: Done. To start the web interface, enter the following command:
==> default: $ vagrant ssh -c "cd /srv/Mailpile && ./mp --www=0.0.0.0:33411 --wait"


$ vagrant ssh -c "cd /srv/Mailpile && ./mp --www=0.0.0.0:33411 --wait"
Failed to configure i18n. Using fallback.                                      
Traceback (most recent call last):                                             
  File "./mp", line 12, in <module>
    Main(sys.argv[1:])
  File "/srv/Mailpile/mailpile/app.py", line 144, in Main
    config.load(session)
  File "/srv/Mailpile/mailpile/config.py", line 1233, in load
    return self._unlocked_load(*args, **kwargs)
  File "/srv/Mailpile/mailpile/config.py", line 1292, in _unlocked_load
    self.load_plugins(session)
  File "/srv/Mailpile/mailpile/config.py", line 1334, in load_plugins
    self.plugins.load(plugin)
  File "/srv/Mailpile/mailpile/plugins/__init__.py", line 201, in load
    return self._load(*args, **kwargs)
  File "/srv/Mailpile/mailpile/plugins/__init__.py", line 153, in _load
    module = __import__(full_name)
  File "/srv/Mailpile/mailpile/plugins/keylookup/__init__.py", line 342, in <module>
    from mailpile.plugins.keylookup.email_keylookup import EmailKeyLookupHandler
  File "/srv/Mailpile/mailpile/plugins/keylookup/email_keylookup.py", line 11, in <module>
    import pgpdump
ImportError: No module named pgpdump
Connection to 127.0.0.1 closed.
```

**Comment by BjarniRunar** [comment]
This is obsolete. Vagrant support may still be broken since it's an orphan (I am unaware of anyone using it), but this bug is too old to be actionable. Thanks for filing though!
